<?php

require 'auth.php';
require 'config.php';

perm_require('page.stock_report');

$lang = $_GET['lang'] ?? 'ar';
$dir  = $lang === 'ar' ? 'rtl' : 'ltr';

/* ─── Motivational Quote (edit here) ─── */
$quotes = [
    'ar' => [
        'text'   => 'النجاح ليس نهاية الطريق، والفشل ليس نهاية المطاف — الشجاعة هي ما يهم.',
        'author' => 'ونستون تشرشل'
    ],
    'en' => [
        'text'   => 'Success is not final, failure is not fatal — it is the courage to continue that counts.',
        'author' => 'Winston Churchill'
    ],
];
$quote = $quotes[$lang];

/* ─── Translations ─── */
$t = [
    'ar' => [
        'title'          => 'تقرير المخزون',
        'subtitle'       => 'السيارات المتاحة فقط',
        'year'           => 'سنة الصنع',
        'dashboard'      => 'الرئيسية',
        'inventory'      => 'المخزون',
        'total_cars'     => 'إجمالي السيارات',
        'branches'       => 'الفروع',
        'brands'         => 'الماركات',
        'search'         => 'بحث بالشاسيه أو الموديل أو اللون...',
        'all_branches'   => 'كل الفروع',
        'all_brands'     => 'كل الماركات',
        'brand'          => 'الماركة',
        'model'          => 'الموديل',
        'trim'           => 'الفئة',
        'color'          => 'اللون',
        'chassis'        => 'الشاسيه',
        'notes'          => 'ملاحظات',
        'branch'         => 'الفرع',
        'print'          => 'طباعة',
        'pdf'            => 'تحميل PDF',
        'available_only' => 'إجمالي السيارات المتاحة',
        'date_from'      => 'من تاريخ',
        'date_to'        => 'إلى تاريخ',
        'reset'          => 'إعادة تعيين',
        'no_cars'        => '🚗 لا توجد سيارات متاحة',
        'reserved'       => 'محجوزة',
        'cars_count'     => 'سيارة',
        'generated_by'   => 'أعده',
        'generated_at'   => 'بتاريخ',
        'amana_section'  => '🔶 سيارات الأمانة',
        'amana_dealer'   => 'التاجر',
        'amana_since'    => 'تاريخ الخروج',
        'amana_total'    => 'إجمالي سيارات الأمانة',
        'search_btn'     => 'بحث',
    ],
    'en' => [
        'title'          => 'Stock Report',
        'subtitle'       => 'Available Vehicles Only',
        'dashboard'      => 'Dashboard',
        'inventory'      => 'Inventory',
        'total_cars'     => 'Total Vehicles',
        'branches'       => 'Branches',
        'brands'         => 'Brands',
        'search'         => 'Search by Chassis, Model or Color...',
        'all_branches'   => 'All Branches',
        'all_brands'     => 'All Brands',
        'year'           => 'Year',
        'brand'          => 'Brand',
        'model'          => 'Model',
        'trim'           => 'Trim',
        'color'          => 'Color',
        'chassis'        => 'Chassis',
        'notes'          => 'Notes',
        'branch'         => 'Branch',
        'print'          => 'Print',
        'pdf'            => 'Download PDF',
        'available_only' => 'Total Available Vehicles',
        'date_from'      => 'Date From',
        'date_to'        => 'Date To',
        'reset'          => 'Reset',
        'no_cars'        => '🚗 No Available Vehicles Found',
        'reserved'       => 'Reserved',
        'cars_count'     => 'Cars',
        'generated_by'   => 'Generated By',
        'generated_at'   => 'Generated At',
        'amana_section'  => '🔶 Consignment Vehicles',
        'amana_dealer'   => 'Dealer',
        'amana_since'    => 'Out Since',
        'amana_total'    => 'Total Consignment Vehicles',
        'search_btn'     => 'Search',
    ],
];

/* ─── Filters ─── */
$search         = trim($_GET['search']      ?? '');
$selectedBranch = trim($_GET['branch']      ?? '');
$selectedBrand  = trim($_GET['brand']       ?? '');
$dateFrom       = trim($_GET['date_from']   ?? '');
$dateTo         = trim($_GET['date_to']     ?? '');

// Reserved cars stay in the stock report — they're still in stock, just gold.
$where  = ["status IN ('available','reserved')"];
$params = [];

if ($search !== '') {
    $where[] = "(brand LIKE ? OR model LIKE ? OR trim_name LIKE ? OR car_year LIKE ? OR color LIKE ? OR chassis LIKE ? OR branch LIKE ? OR notes LIKE ?)";
    for ($i = 0; $i < 8; $i++) $params[] = "%$search%";
}
if ($selectedBranch !== '') { $where[] = "branch = ?";     $params[] = $selectedBranch; }
if ($selectedBrand  !== '') { $where[] = "brand = ?";      $params[] = $selectedBrand; }
if ($dateFrom       !== '') { $where[] = "created_at >= ?"; $params[] = $dateFrom . ' 00:00:00'; }
if ($dateTo         !== '') { $where[] = "created_at <= ?"; $params[] = $dateTo   . ' 23:59:59'; }

$sql = "SELECT * FROM cars WHERE " . implode(' AND ', $where) . " ORDER BY branch, brand, model, trim_name";
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$cars = $stmt->fetchAll(PDO::FETCH_ASSOC);

$totalCars   = count($cars);
$branchCount = $pdo->query("SELECT COUNT(*) FROM branches")->fetchColumn();
$brandCount  = $pdo->query("SELECT COUNT(DISTINCT brand) FROM cars WHERE status IN ('available','reserved')")->fetchColumn();

$branches = $pdo->query("SELECT * FROM branches ORDER BY name_en")->fetchAll(PDO::FETCH_ASSOC);
$brands   = $pdo->query("SELECT DISTINCT brand FROM cars WHERE status IN ('available','reserved') ORDER BY brand")->fetchAll(PDO::FETCH_ASSOC);

/* ─── امانة (consignment) cars — permission-gated (default: admin/manager) ─── */
$canSeeAmana = can('stock.amana');
$amanaCars   = [];
if ($canSeeAmana) {
    // Same filters as the main report, but for consignment cars,
    // joined to their active consignment record for the dealer name.
    $aWhere  = ["c.status = 'consignment'"];
    $aParams = [];
    if ($search !== '') {
        $aWhere[] = "(c.brand LIKE ? OR c.model LIKE ? OR c.trim_name LIKE ? OR c.car_year LIKE ? OR c.color LIKE ? OR c.chassis LIKE ? OR c.branch LIKE ? OR cn.dealer_name LIKE ?)";
        for ($i = 0; $i < 8; $i++) $aParams[] = "%$search%";
    }
    if ($selectedBranch !== '') { $aWhere[] = "c.branch = ?"; $aParams[] = $selectedBranch; }
    if ($selectedBrand  !== '') { $aWhere[] = "c.brand = ?";  $aParams[] = $selectedBrand; }
    if ($dateFrom       !== '') { $aWhere[] = "cn.started_at >= ?"; $aParams[] = $dateFrom . ' 00:00:00'; }
    if ($dateTo         !== '') { $aWhere[] = "cn.started_at <= ?"; $aParams[] = $dateTo   . ' 23:59:59'; }

    $aSql = "
        SELECT c.*, cn.dealer_name, cn.salesman, cn.started_at
        FROM cars c
        LEFT JOIN consignments cn ON cn.car_id = c.id AND cn.status = 'active'
        WHERE " . implode(' AND ', $aWhere) . "
        ORDER BY c.branch, c.brand, c.model, c.trim_name
    ";
    $aStmt = $pdo->prepare($aSql);
    $aStmt->execute($aParams);
    $amanaCars = $aStmt->fetchAll(PDO::FETCH_ASSOC);
}

/* ─── Auto-trigger print dialog when ?print=1 ─── */
$autoPrint = isset($_GET['print']) && $_GET['print'] === '1';

?>
<!DOCTYPE html>
<html lang="<?= $lang ?>" dir="<?= $dir ?>">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?= $t[$lang]['title'] ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;900&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">

<style>
*, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }

:root {
    --bg-deep:      #020617;
    --bg-surface:   #0b1221;
    --bg-card:      rgba(15,23,42,.92);
    --border:       rgba(255,255,255,.07);
    --green:        #22c55e;
    --green-dim:    rgba(34,197,94,.12);
    --purple:       #9333ea;
    --purple-dim:   rgba(147,51,234,.12);
    --blue:         #2563eb;
    --amber:        #f59e0b;
    --amber-dim:    rgba(245,158,11,.10);
    --text:         #f1f5f9;
    --muted:        #64748b;
    --muted-light:  #94a3b8;
    --radius-card:  20px;
    --radius-btn:   12px;
    --radius-input: 12px;
    --font-ar:      'Cairo', sans-serif;
    --font-en:      'Inter', sans-serif;
    --shadow:       0 4px 24px rgba(0,0,0,.4);
}

html[lang="ar"] body { font-family: var(--font-ar); }
html[lang="en"] body { font-family: var(--font-en); }

body {
    background: linear-gradient(150deg, #020617 0%, #0a0f1e 50%, #05101f 100%);
    color: var(--text);
    min-height: 100vh;
    padding-bottom: 80px;
}

.wrap { max-width: 1600px; margin: auto; padding: 16px 20px; }

.quote-banner {
    background: linear-gradient(90deg, rgba(34,197,94,.08) 0%, rgba(147,51,234,.10) 100%);
    border: 1px solid rgba(34,197,94,.18);
    border-radius: var(--radius-card);
    padding: 14px 22px;
    display: flex;
    align-items: center;
    gap: 14px;
    margin-bottom: 18px;
    position: relative;
    overflow: hidden;
}
.quote-banner::before {
    content: '';
    position: absolute;
    inset: 0;
    background: radial-gradient(ellipse at 0% 50%, rgba(34,197,94,.06), transparent 60%);
    pointer-events: none;
}
.quote-icon { font-size: 26px; flex-shrink: 0; }
.quote-text { font-size: 13.5px; color: #cbd5e1; line-height: 1.65; }
.quote-author { font-size: 12px; color: var(--green); font-weight: 700; margin-top: 4px; }

.header {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    padding: 20px 24px;
    margin-bottom: 18px;
    backdrop-filter: blur(20px);
    box-shadow: var(--shadow);
}
.header-top {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 16px;
    flex-wrap: wrap;
}
.page-title {
    font-size: 28px;
    font-weight: 900;
    background: linear-gradient(90deg, var(--green), #86efac);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    line-height: 1.2;
}
.page-subtitle { font-size: 13px; color: var(--muted-light); margin-top: 4px; }

.nav-group { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }

.nav-btn {
    text-decoration: none;
    padding: 9px 16px;
    border-radius: var(--radius-btn);
    font-weight: 700;
    font-size: 13px;
    color: white;
    transition: transform .2s, box-shadow .2s;
    display: flex;
    align-items: center;
    gap: 6px;
}
.nav-btn:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,.35); }
.nav-btn.dash   { background: var(--blue); }
.nav-btn.inv    { background: var(--green); color: #002b14; }
.nav-btn.report { background: var(--purple); }

.lang-row { display: flex; gap: 8px; margin-top: 14px; }
.lang-btn {
    text-decoration: none;
    padding: 7px 14px;
    border-radius: 10px;
    background: #111827;
    color: var(--muted-light);
    font-size: 12px;
    font-weight: 700;
    border: 1px solid var(--border);
    transition: background .2s;
}
.lang-btn.active { background: var(--purple); color: white; border-color: transparent; }

.stats-row {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 14px;
    margin-bottom: 18px;
}
.stat-card {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    padding: 22px 18px;
    text-align: center;
    position: relative;
    overflow: hidden;
    box-shadow: var(--shadow);
}
.stat-card::after {
    content: '';
    position: absolute;
    bottom: 0; left: 0; right: 0;
    height: 3px;
}
.stat-card.c-total::after  { background: linear-gradient(90deg, var(--green), #86efac); }
.stat-card.c-branch::after { background: linear-gradient(90deg, var(--blue), #60a5fa); }
.stat-card.c-brand::after  { background: linear-gradient(90deg, var(--purple), #c084fc); }

.stat-label { font-size: 12px; text-transform: uppercase; letter-spacing: .06em; color: var(--muted); font-weight: 700; }
.stat-number { font-size: 48px; font-weight: 900; margin-top: 6px; line-height: 1; }
.c-total  .stat-number { color: var(--green); }
.c-branch .stat-number { color: #60a5fa; }
.c-brand  .stat-number { color: #c084fc; }

.filters-card {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    padding: 20px 22px;
    margin-bottom: 18px;
    box-shadow: var(--shadow);
}
.filter-grid {
    display: grid;
    grid-template-columns: 2fr 1fr 1fr 1fr 1fr auto auto;
    gap: 10px;
    align-items: end;
}
.filter-group { display: flex; flex-direction: column; gap: 5px; }
.filter-label { font-size: 11px; font-weight: 700; color: var(--muted); text-transform: uppercase; letter-spacing: .05em; }

input[type="text"],
input[type="date"],
select {
    width: 100%;
    height: 48px;
    border: 1px solid rgba(255,255,255,.08);
    outline: none;
    background: #0d1526;
    color: var(--text);
    padding: 0 14px;
    border-radius: var(--radius-input);
    font-size: 14px;
    transition: border-color .2s, box-shadow .2s;
    font-family: inherit;
    -webkit-appearance: none;
    appearance: none;
}
input:focus, select:focus {
    border-color: var(--green);
    box-shadow: 0 0 0 3px rgba(34,197,94,.12);
}
select { cursor: pointer; }
select option { background: #0d1526; }

input[type="date"]::-webkit-calendar-picker-indicator { filter: invert(1) opacity(.5); cursor: pointer; }

.btn-search {
    height: 48px;
    padding: 0 22px;
    border: none;
    border-radius: var(--radius-btn);
    font-weight: 800;
    font-size: 14px;
    cursor: pointer;
    background: linear-gradient(90deg, var(--green), #16a34a);
    color: #002b14;
    font-family: inherit;
    transition: transform .2s, box-shadow .2s;
    white-space: nowrap;
}
.btn-search:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(34,197,94,.3); }

.btn-reset {
    height: 48px;
    padding: 0 18px;
    border: 1px solid var(--border);
    border-radius: var(--radius-btn);
    font-weight: 700;
    font-size: 13px;
    cursor: pointer;
    background: #111827;
    color: var(--muted-light);
    text-decoration: none;
    display: flex;
    align-items: center;
    gap: 6px;
    font-family: inherit;
    transition: border-color .2s;
    white-space: nowrap;
}
.btn-reset:hover { border-color: var(--muted); }

.table-card {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    padding: 24px;
    box-shadow: var(--shadow);
}

.branch-section { margin-bottom: 36px; }

.branch-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 12px;
    padding-bottom: 12px;
    border-bottom: 1px solid rgba(255,255,255,.06);
    gap: 10px;
    flex-wrap: wrap;
}
.branch-title {
    font-size: 18px;
    font-weight: 800;
    color: var(--green);
    display: flex;
    align-items: center;
    gap: 8px;
}
.branch-badge {
    background: var(--green-dim);
    color: var(--green);
    padding: 5px 14px;
    border-radius: 50px;
    font-size: 12px;
    font-weight: 800;
    border: 1px solid rgba(34,197,94,.2);
}

.inv-table { width: 100%; border-collapse: collapse; }
.inv-table thead tr { background: #0d1526; }
.inv-table th {
    padding: 12px 14px;
    text-align: center;
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: .05em;
    color: var(--muted);
    white-space: nowrap;
}
.inv-table td {
    padding: 11px 14px;
    text-align: center;
    border-bottom: 1px solid rgba(255,255,255,.04);
    font-size: 13.5px;
}
.inv-table tr:last-child td { border-bottom: none; }
.inv-table tbody tr { transition: background .15s; }
.inv-table tbody tr:hover { background: rgba(34,197,94,.04); }

/* ── 🔒 محجوزة / Reserved — golden row ── */
.inv-table tbody tr.res-row {
    background: linear-gradient(90deg, rgba(250,204,21,.10), rgba(234,179,8,.04));
    box-shadow: inset 3px 0 0 #facc15;
}
.inv-table tbody tr.res-row:hover { background: rgba(250,204,21,.16); }
.inv-table tbody tr.res-row td { color: #fde68a; }
.res-badge {
    display: inline-block; font-size: 10px; font-weight: 800;
    padding: 2px 8px; border-radius: 20px; white-space: nowrap;
    background: rgba(250,204,21,.18); color: #facc15;
    border: 1px solid rgba(250,204,21,.45);
}

.num-cell { color: var(--muted); font-size: 12px; }
.chassis-cell { font-family: 'Courier New', monospace; font-size: 12px; color: var(--muted-light); letter-spacing: .04em; }
.brand-cell { font-weight: 700; color: #e2e8f0; }

.notes-cell {
    font-size: 12.5px;
    color: var(--muted);
    text-align: start;
    max-width: 220px;
    white-space: normal;
    word-break: break-word;
}
.notes-cell.has-note {
    color: #fcd34d;
    font-weight: 600;
}

.empty-state {
    text-align: center;
    padding: 60px 20px;
    color: var(--muted);
}
.empty-state .e-icon { font-size: 48px; margin-bottom: 12px; }
.empty-state p { font-size: 16px; }

.actions-bar {
    display: flex;
    gap: 12px;
    justify-content: center;
    margin-top: 24px;
    flex-wrap: wrap;
}
.act-btn {
    text-decoration: none;
    border: none;
    cursor: pointer;
    padding: 13px 26px;
    border-radius: var(--radius-btn);
    font-size: 14px;
    font-weight: 800;
    color: white;
    display: flex;
    align-items: center;
    gap: 8px;
    font-family: inherit;
    transition: transform .2s, box-shadow .2s;
}
.act-btn:hover { transform: translateY(-2px); }
.act-print { background: var(--green); color: #002b14; }
.act-print:hover { box-shadow: 0 6px 20px rgba(34,197,94,.3); }

.report-footer {
    margin-top: 20px;
    padding: 16px 22px;
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 10px;
    font-size: 13px;
    color: var(--muted-light);
}
.report-footer strong { color: var(--text); }

.grand-card {
    margin-top: 20px;
    background: linear-gradient(135deg, rgba(34,197,94,.15) 0%, rgba(147,51,234,.15) 100%);
    border: 1px solid rgba(34,197,94,.25);
    border-radius: var(--radius-card);
    padding: 28px;
    text-align: center;
}
.grand-label { font-size: 15px; font-weight: 700; color: var(--muted-light); }

/* ── امانة report block (amber) ── */
.amana-report-card { margin-top: 22px; }
.amana-report-header { background: rgba(245,158,11,.1) !important; border-color: rgba(245,158,11,.3) !important; }
.amana-report-badge { background: rgba(245,158,11,.2) !important; color: #f59e0b !important; }
.amana-dealer-cell { color: #b45309; font-weight: 700; }
.amana-grand-card {
    background: linear-gradient(135deg, rgba(245,158,11,.15) 0%, rgba(249,115,22,.15) 100%) !important;
    border: 1px solid rgba(245,158,11,.3) !important;
}
.amana-grand-card .grand-number {
    background: linear-gradient(90deg, #f59e0b, #f97316) !important;
    -webkit-background-clip: text; background-clip: text;
}
@media print {
    .amana-report-header { background: #fdf0d5 !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .amana-dealer-cell { color: #92400e !important; }
}
.grand-number {
    font-size: 72px;
    font-weight: 900;
    line-height: 1;
    margin-top: 8px;
    background: linear-gradient(90deg, var(--green), var(--purple));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

@media (max-width: 1100px) {
    .filter-grid { grid-template-columns: 1fr 1fr; }
}
@media (max-width: 700px) {
    .stats-row { grid-template-columns: 1fr; }
    .filter-grid { grid-template-columns: 1fr; }
    .header-top { flex-direction: column; align-items: flex-start; }
    .stat-number { font-size: 38px; }
    .grand-number { font-size: 52px; }
    .inv-table { display: block; overflow-x: auto; white-space: nowrap; }
    .page-title { font-size: 22px; }
    .notes-cell { max-width: none; white-space: nowrap; }
}

/* ═══════════════════════════════════════
   PRINT — COMPACT, FIT ON ONE PAGE
═══════════════════════════════════════ */
@media print {
    @page { size: A4 landscape; margin: 6mm 6mm; }

    html, body {
        background: white !important;
        color: black !important;
        font-size: 7px !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
    }

    .quote-banner,
    .header .nav-group,
    .lang-row,
    .filters-card,
    .actions-bar,
    .report-footer { display: none !important; }

    .wrap { padding: 0 !important; max-width: 100% !important; }

    .header {
        background: white !important;
        border: none !important;
        box-shadow: none !important;
        padding: 0 0 4px 0 !important;
        margin-bottom: 4px !important;
    }
    .page-title {
        font-size: 13px !important;
        -webkit-text-fill-color: #1a1a1a !important;
        color: #1a1a1a !important;
        background: none !important;
        margin: 0 !important;
    }
    .page-subtitle { color: #555 !important; font-size: 8px !important; }

    .stats-row {
        gap: 4px !important;
        margin-bottom: 5px !important;
        grid-template-columns: repeat(3, 1fr) !important;
    }
    .stat-card {
        background: #f5f5f5 !important;
        border: 1px solid #ddd !important;
        padding: 3px 6px !important;
        box-shadow: none !important;
        border-radius: 6px !important;
    }
    .stat-card::after { display: none !important; }
    .stat-label { color: #555 !important; font-size: 7px !important; }
    .stat-number { font-size: 14px !important; margin-top: 1px !important; }
    .c-total  .stat-number { color: #16a34a !important; }
    .c-branch .stat-number { color: #1d4ed8 !important; }
    .c-brand  .stat-number { color: #7e22ce !important; }

    .table-card {
        background: white !important;
        border: none !important;
        box-shadow: none !important;
        padding: 0 !important;
    }

    .branch-section {
        page-break-inside: auto;
        margin-bottom: 6px !important;
    }
    .branch-header {
        padding-bottom: 3px !important;
        margin-bottom: 3px !important;
        border-bottom: 1px solid #ccc !important;
    }
    .branch-title { color: #15803d !important; font-size: 9px !important; gap: 4px !important; }
    .branch-badge {
        background: #dcfce7 !important;
        color: #15803d !important;
        border: 1px solid #86efac !important;
        font-size: 7px !important;
        padding: 1px 7px !important;
    }

    .inv-table { width: 100% !important; }
    .inv-table th {
        background: #1e293b !important;
        color: white !important;
        font-size: 7px !important;
        padding: 2px 4px !important;
        letter-spacing: 0 !important;
    }
    .inv-table td {
        font-size: 7px !important;
        padding: 1.5px 4px !important;
        color: black !important;
        border-bottom: 1px solid #e5e7eb !important;
        line-height: 1.2 !important;
    }
    .inv-table tbody tr { page-break-inside: avoid !important; }
    .chassis-cell { color: #374151 !important; font-size: 6.5px !important; }
    .brand-cell   { color: black !important; }
    .notes-cell, .notes-cell.has-note {
        color: #92400e !important;
        font-weight: 600 !important;
        max-width: 140px !important;
        white-space: normal !important;
    }

    .grand-card {
        background: white !important;
        border: 1.5px solid #000 !important;
        padding: 6px !important;
        margin-top: 6px !important;
        border-radius: 6px !important;
        page-break-inside: avoid !important;
    }
    .grand-label { color: #333 !important; font-size: 9px !important; }
    .grand-number {
        -webkit-text-fill-color: #111 !important;
        background: none !important;
        color: #111 !important;
        font-size: 22px !important;
        margin-top: 2px !important;
    }
}
</style>
</head>
<body>
<div class="wrap">

    <!-- ── QUOTE BANNER ──────────────────────────────── -->
    <div class="quote-banner">
        <span class="quote-icon">💬</span>
        <div>
            <div class="quote-text">«<?= htmlspecialchars($quote['text']) ?>»</div>
            <div class="quote-author">— <?= htmlspecialchars($quote['author']) ?></div>
        </div>
    </div>

    <!-- ── HEADER ────────────────────────────────────── -->
    <div class="header">
        <div class="header-top">
            <div>
                <div class="page-title">📄 <?= $t[$lang]['title'] ?></div>
                <div class="page-subtitle"><?= $t[$lang]['subtitle'] ?></div>
            </div>
            <div class="nav-group">
                <a href="dashboard.php?lang=<?= $lang ?>"  class="nav-btn dash">🏠 <?= $t[$lang]['dashboard'] ?></a>
                <a href="dashboard.php?lang=<?= $lang ?>"  class="nav-btn inv">🚗 <?= $t[$lang]['inventory'] ?></a>
                <a href="stock_report.php?lang=<?= $lang ?>" class="nav-btn report">📄 <?= $t[$lang]['title'] ?></a>
            </div>
        </div>
        <div class="lang-row">
            <a href="?lang=ar&search=<?= urlencode($search) ?>&branch=<?= urlencode($selectedBranch) ?>&brand=<?= urlencode($selectedBrand) ?>&date_from=<?= urlencode($dateFrom) ?>&date_to=<?= urlencode($dateTo) ?>"
               class="lang-btn <?= $lang === 'ar' ? 'active' : '' ?>">🇪🇬 العربية</a>
            <a href="?lang=en&search=<?= urlencode($search) ?>&branch=<?= urlencode($selectedBranch) ?>&brand=<?= urlencode($selectedBrand) ?>&date_from=<?= urlencode($dateFrom) ?>&date_to=<?= urlencode($dateTo) ?>"
               class="lang-btn <?= $lang === 'en' ? 'active' : '' ?>">🇺🇸 English</a>
        </div>
    </div>

    <!-- ── STATS ─────────────────────────────────────── -->
    <div class="stats-row">
        <div class="stat-card c-total">
            <div class="stat-label"><?= $t[$lang]['total_cars'] ?></div>
            <div class="stat-number"><?= $totalCars ?></div>
        </div>
        <div class="stat-card c-branch">
            <div class="stat-label"><?= $t[$lang]['branches'] ?></div>
            <div class="stat-number"><?= $branchCount ?></div>
        </div>
        <div class="stat-card c-brand">
            <div class="stat-label"><?= $t[$lang]['brands'] ?></div>
            <div class="stat-number"><?= $brandCount ?></div>
        </div>
    </div>

    <!-- ── FILTERS ───────────────────────────────────── -->
    <form method="GET" class="filters-card">
        <input type="hidden" name="lang" value="<?= $lang ?>">
        <div class="filter-grid">

            <div class="filter-group">
                <span class="filter-label">🔍 <?= $t[$lang]['search'] ?></span>
                <input type="text" name="search"
                       placeholder="<?= $t[$lang]['search'] ?>"
                       value="<?= htmlspecialchars($search) ?>">
            </div>

            <div class="filter-group">
                <span class="filter-label">📍 <?= $t[$lang]['branch'] ?></span>
                <select name="branch">
                    <option value=""><?= $t[$lang]['all_branches'] ?></option>
                    <?php foreach ($branches as $b): ?>
                    <option value="<?= htmlspecialchars($b['name']) ?>"
                        <?= $selectedBranch === $b['name'] ? 'selected' : '' ?>>
                        <?= htmlspecialchars($lang === 'ar' ? $b['name_ar'] : $b['name_en']) ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="filter-group">
                <span class="filter-label">🚘 <?= $t[$lang]['brand'] ?></span>
                <select name="brand">
                    <option value=""><?= $t[$lang]['all_brands'] ?></option>
                    <?php foreach ($brands as $b): ?>
                    <option value="<?= htmlspecialchars($b['brand']) ?>"
                        <?= $selectedBrand === $b['brand'] ? 'selected' : '' ?>>
                        <?= htmlspecialchars($b['brand']) ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="filter-group">
                <span class="filter-label">📅 <?= $t[$lang]['date_from'] ?></span>
                <input type="date" name="date_from" value="<?= htmlspecialchars($dateFrom) ?>">
            </div>

            <div class="filter-group">
                <span class="filter-label">📅 <?= $t[$lang]['date_to'] ?></span>
                <input type="date" name="date_to" value="<?= htmlspecialchars($dateTo) ?>">
            </div>

            <button type="submit" class="btn-search">🔍 <?= $t[$lang]['search_btn'] ?></button>

            <a href="stock_report.php?lang=<?= $lang ?>" class="btn-reset">✕ <?= $t[$lang]['reset'] ?></a>
        </div>
    </form>

    <!-- ── TABLE ─────────────────────────────────────── -->
    <div class="table-card">
        <?php if (count($cars) === 0): ?>
        <div class="empty-state">
            <div class="e-icon">🚗</div>
            <p><?= $t[$lang]['no_cars'] ?></p>
        </div>
        <?php else:
            $currentBranch = '';
            $counter = 1;
            foreach ($cars as $car):
                if ($currentBranch !== $car['branch']):
                    if ($currentBranch !== '') { echo '</tbody></table></div>'; }
                    $currentBranch = $car['branch'];

                    $bStmt = $pdo->prepare("SELECT name_ar,name_en FROM branches WHERE name=? LIMIT 1");
                    $bStmt->execute([$currentBranch]);
                    $bData = $bStmt->fetch(PDO::FETCH_ASSOC);
                    $bDisplay = $bData
                        ? ($lang === 'ar' ? $bData['name_ar'] : $bData['name_en'])
                        : $currentBranch;

                    $btWhere  = array_merge($where, ["branch = ?"]);
                    $btParams = array_merge($params, [$currentBranch]);
                    $btSQL    = "SELECT COUNT(*) FROM cars WHERE " . implode(' AND ', $btWhere);
                    $btStmt   = $pdo->prepare($btSQL);
                    $btStmt->execute($btParams);
                    $branchTotal = $btStmt->fetchColumn();

                    $counter = 1;
        ?>
                    <div class="branch-section">
                    <div class="branch-header">
                        <div class="branch-title">📍 <?= htmlspecialchars($bDisplay) ?></div>
                        <div class="branch-badge"><?= $branchTotal ?> <?= $t[$lang]['cars_count'] ?></div>
                    </div>
                    <table class="inv-table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><?= $t[$lang]['brand'] ?></th>
                                <th><?= $t[$lang]['model'] ?></th>
                                <th><?= $t[$lang]['trim'] ?></th>
                                <th><?= $t[$lang]['year'] ?></th>
                                <th><?= $t[$lang]['color'] ?></th>
                                <th><?= $t[$lang]['chassis'] ?></th>
                                <th><?= $t[$lang]['notes'] ?></th>
                            </tr>
                        </thead>
                        <tbody>
        <?php endif; ?>
                        <?php
                            $noteText   = trim((string)($car['notes'] ?? ''));
                            $isReserved = (($car['status'] ?? '') === 'reserved');
                        ?>
                        <tr class="<?= $isReserved ? 'res-row' : '' ?>">
                            <td class="num-cell"><?= $counter++ ?></td>
                            <td class="brand-cell">
                                <?php if ($isReserved): ?><span class="res-badge">🔒 <?= $t[$lang]['reserved'] ?></span> <?php endif; ?>
                                <?= htmlspecialchars($car['brand']) ?>
                            </td>
                            <td><?= htmlspecialchars($car['model']) ?></td>
                            <td><?= htmlspecialchars($car['trim_name']) ?></td>
                            <td><?= htmlspecialchars($car['car_year']) ?></td>
                            <td>
                            <?php
                                $cStmt = $pdo->prepare("SELECT color_ar,color_en FROM colors WHERE color_en=? LIMIT 1");
                                $cStmt->execute([$car['color']]);
                                $cData = $cStmt->fetch(PDO::FETCH_ASSOC);
                                $cDisplay = $cData
                                    ? ($lang === 'ar' ? $cData['color_ar'] : $cData['color_en'])
                                    : $car['color'];
                                echo htmlspecialchars($cDisplay);
                            ?>
                            </td>
                            <td class="chassis-cell"><?= htmlspecialchars($car['chassis']) ?></td>
                            <td class="notes-cell <?= $noteText !== '' ? 'has-note' : '' ?>">
                                <?= $noteText !== '' ? '📝 ' . htmlspecialchars($noteText) : '—' ?>
                            </td>
                        </tr>
        <?php endforeach; ?>
                        </tbody>
                    </table>
                    </div>
        <?php endif; ?>
    </div><!-- /.table-card -->

    <?php if ($canSeeAmana && !empty($amanaCars)): ?>
    <!-- ── امانة / CONSIGNMENT (admin/manager only) ─────── -->
    <div class="table-card amana-report-card">
        <div class="branch-section">
            <div class="branch-header amana-report-header">
                <div class="branch-title"><?= $t[$lang]['amana_section'] ?></div>
                <div class="branch-badge amana-report-badge"><?= count($amanaCars) ?> <?= $t[$lang]['cars_count'] ?></div>
            </div>
            <table class="inv-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th><?= $t[$lang]['brand'] ?></th>
                        <th><?= $t[$lang]['model'] ?></th>
                        <th><?= $t[$lang]['trim'] ?></th>
                        <th><?= $t[$lang]['year'] ?></th>
                        <th><?= $t[$lang]['color'] ?></th>
                        <th><?= $t[$lang]['chassis'] ?></th>
                        <th><?= $t[$lang]['branch'] ?></th>
                        <th><?= $t[$lang]['amana_dealer'] ?></th>
                        <th><?= $t[$lang]['amana_since'] ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $ac = 1; foreach ($amanaCars as $car):
                        $cStmt = $pdo->prepare("SELECT color_ar,color_en FROM colors WHERE color_en=? LIMIT 1");
                        $cStmt->execute([$car['color']]);
                        $cData = $cStmt->fetch(PDO::FETCH_ASSOC);
                        $cDisplay = $cData ? ($lang === 'ar' ? $cData['color_ar'] : $cData['color_en']) : $car['color'];

                        $bStmt = $pdo->prepare("SELECT name_ar,name_en FROM branches WHERE name=? LIMIT 1");
                        $bStmt->execute([$car['branch']]);
                        $bData = $bStmt->fetch(PDO::FETCH_ASSOC);
                        $bDisplay = $bData ? ($lang === 'ar' ? $bData['name_ar'] : $bData['name_en']) : $car['branch'];

                        $sinceFmt = !empty($car['started_at']) ? date('Y-m-d', strtotime($car['started_at'])) : '—';
                    ?>
                    <tr>
                        <td class="num-cell"><?= $ac++ ?></td>
                        <td class="brand-cell"><?= htmlspecialchars($car['brand']) ?></td>
                        <td><?= htmlspecialchars($car['model']) ?></td>
                        <td><?= htmlspecialchars($car['trim_name']) ?></td>
                        <td><?= htmlspecialchars($car['car_year']) ?></td>
                        <td><?= htmlspecialchars($cDisplay) ?></td>
                        <td class="chassis-cell"><?= htmlspecialchars($car['chassis']) ?></td>
                        <td><?= htmlspecialchars($bDisplay) ?></td>
                        <td class="amana-dealer-cell"><?= htmlspecialchars($car['dealer_name'] ?? '—') ?></td>
                        <td><?= htmlspecialchars($sinceFmt) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="grand-card amana-grand-card">
        <div class="grand-label"><?= $t[$lang]['amana_total'] ?></div>
        <div class="grand-number"><?= count($amanaCars) ?></div>
    </div>
    <?php endif; ?>

    <!-- ── ACTIONS ───────────────────────────────────── -->
    <div class="actions-bar">
        <button type="button" onclick="window.print()" class="act-btn act-print">
            🖨 <?= $t[$lang]['print'] ?>
        </button>
    </div>

    <!-- ── FOOTER ────────────────────────────────────── -->
    <div class="report-footer">
        <div><?= $t[$lang]['generated_by'] ?>: <strong><?= htmlspecialchars($_SESSION['username']) ?></strong></div>
        <div><?= $t[$lang]['generated_at'] ?>: <strong><?= date('d M Y  h:i A') ?></strong></div>
    </div>

    <!-- ── GRAND TOTAL ───────────────────────────────── -->
    <div class="grand-card">
        <div class="grand-label">🚗 <?= $t[$lang]['available_only'] ?></div>
        <div class="grand-number"><?= $totalCars ?></div>
    </div>

</div><!-- /.wrap -->

<script>
<?php if ($autoPrint): ?>
    window.addEventListener('load', function () {
        setTimeout(function () { window.print(); }, 400);
    });
<?php endif; ?>
</script>
</body>
</html>
