<?php

require 'auth.php';
require 'config.php';
require 'car_images_helpers.php';

perm_require('page.stock_report');

$lang = $_GET['lang'] ?? 'ar';
$dir  = $lang === 'ar' ? 'rtl' : 'ltr';

/* ─── Motivational Quote (edit here) ─── */
$quotes = [
    'ar' => [
        'text'   => 'النجاح ليس نهاية الطريق، والفشل ليس نهاية المطاف — الشجاعة هي ما يهم.',
        'author' => 'ونستون تشرشل'
    ],
    'en' => [
        'text'   => 'Success is not final, failure is not fatal — it is the courage to continue that counts.',
        'author' => 'Winston Churchill'
    ],
];
$quote = $quotes[$lang];

/* ─── Translations ─── */
$t = [
    'ar' => [
        'title'          => 'تقرير المخزون',
        'subtitle'       => 'السيارات المتاحة فقط',
        'year'           => 'سنة الصنع',
        'dashboard'      => 'الرئيسية',
        'inventory'      => 'المخزون',
        'total_cars'     => 'إجمالي السيارات',
        'branches'       => 'الفروع',
        'brands'         => 'الماركات',
        'search'         => 'بحث بالشاسيه أو الموديل أو اللون...',
        'all_branches'   => 'كل الفروع',
        'all_brands'     => 'كل الماركات',
        'brand'          => 'الماركة',
        'model'          => 'الموديل',
        'trim'           => 'الفئة',
        'color'          => 'اللون',
        'chassis'        => 'الشاسيه',
        'notes'          => 'ملاحظات',
        'branch'         => 'الفرع',
        'print'          => 'طباعة',
        'pdf'            => 'تحميل PDF',
        'available_only' => 'إجمالي السيارات المتاحة',
        'date_from'      => 'من تاريخ',
        'date_to'        => 'إلى تاريخ',
        'reset'          => 'إعادة تعيين',
        'no_cars'        => '🚗 لا توجد سيارات متاحة',
        'reserved'       => 'محجوزة',
        'cars_count'     => 'سيارة',
        'generated_by'   => 'أعده',
        'generated_at'   => 'بتاريخ',
        'amana_section'  => '🔶 سيارات الأمانة',
        'amana_dealer'   => 'التاجر',
        'amana_since'    => 'تاريخ الخروج',
        'amana_total'    => 'إجمالي سيارات الأمانة',
        'search_btn'     => 'بحث',
    ],
    'en' => [
        'title'          => 'Stock Report',
        'subtitle'       => 'Available Vehicles Only',
        'dashboard'      => 'Dashboard',
        'inventory'      => 'Inventory',
        'total_cars'     => 'Total Vehicles',
        'branches'       => 'Branches',
        'brands'         => 'Brands',
        'search'         => 'Search by Chassis, Model or Color...',
        'all_branches'   => 'All Branches',
        'all_brands'     => 'All Brands',
        'year'           => 'Year',
        'brand'          => 'Brand',
        'model'          => 'Model',
        'trim'           => 'Trim',
        'color'          => 'Color',
        'chassis'        => 'Chassis',
        'notes'          => 'Notes',
        'branch'         => 'Branch',
        'print'          => 'Print',
        'pdf'            => 'Download PDF',
        'available_only' => 'Total Available Vehicles',
        'date_from'      => 'Date From',
        'date_to'        => 'Date To',
        'reset'          => 'Reset',
        'no_cars'        => '🚗 No Available Vehicles Found',
        'reserved'       => 'Reserved',
        'cars_count'     => 'Cars',
        'generated_by'   => 'Generated By',
        'generated_at'   => 'Generated At',
        'amana_section'  => '🔶 Consignment Vehicles',
        'amana_dealer'   => 'Dealer',
        'amana_since'    => 'Out Since',
        'amana_total'    => 'Total Consignment Vehicles',
        'search_btn'     => 'Search',
    ],
];

/* ─── Filters ─── */
$search         = trim($_GET['search']      ?? '');
$selectedBranch = trim($_GET['branch']      ?? '');
$selectedBrand  = trim($_GET['brand']       ?? '');
$dateFrom       = trim($_GET['date_from']   ?? '');
$dateTo         = trim($_GET['date_to']     ?? '');

// Reserved cars stay in the stock report — they're still in stock, just gold.
$where  = ["status IN ('available','reserved')"];
$params = [];

if ($search !== '') {
    $where[] = "(brand LIKE ? OR model LIKE ? OR trim_name LIKE ? OR car_year LIKE ? OR color LIKE ? OR chassis LIKE ? OR branch LIKE ? OR notes LIKE ?)";
    for ($i = 0; $i < 8; $i++) $params[] = "%$search%";
}
if ($selectedBranch !== '') { $where[] = "branch = ?";     $params[] = $selectedBranch; }
if ($selectedBrand  !== '') { $where[] = "brand = ?";      $params[] = $selectedBrand; }
if ($dateFrom       !== '') { $where[] = "created_at >= ?"; $params[] = $dateFrom . ' 00:00:00'; }
if ($dateTo         !== '') { $where[] = "created_at <= ?"; $params[] = $dateTo   . ' 23:59:59'; }

/* The filters above still describe exactly what the page shows, but they are
   now applied instantly in the browser rather than in this query, so typing or
   picking a branch never reloads the page. Every car in stock is sent once and
   the script at the bottom hides, renumbers and recounts to match the filters —
   the result on screen and on paper is the same as the old server-side filter.
   $where / $params are kept for reference and are no longer executed. */
$cars = $pdo->query("SELECT * FROM cars WHERE status IN ('available','reserved') ORDER BY branch, brand, model, trim_name")
            ->fetchAll(PDO::FETCH_ASSOC);

$totalCars   = count($cars);
$branchCount = $pdo->query("SELECT COUNT(*) FROM branches")->fetchColumn();
$brandCount  = $pdo->query("SELECT COUNT(DISTINCT brand) FROM cars WHERE status IN ('available','reserved')")->fetchColumn();

$branches = $pdo->query("SELECT * FROM branches ORDER BY name_en")->fetchAll(PDO::FETCH_ASSOC);
$brands   = $pdo->query("SELECT DISTINCT brand FROM cars WHERE status IN ('available','reserved') ORDER BY brand")->fetchAll(PDO::FETCH_ASSOC);

/* ─── امانة (consignment) cars — permission-gated (default: admin/manager) ─── */
$canSeeAmana = can('stock.amana');
$amanaCars   = [];
if ($canSeeAmana) {
    // Same filters as the main report, but for consignment cars,
    // joined to their active consignment record for the dealer name.
    $aWhere  = ["c.status = 'consignment'"];
    $aParams = [];
    if ($search !== '') {
        $aWhere[] = "(c.brand LIKE ? OR c.model LIKE ? OR c.trim_name LIKE ? OR c.car_year LIKE ? OR c.color LIKE ? OR c.chassis LIKE ? OR c.branch LIKE ? OR cn.dealer_name LIKE ?)";
        for ($i = 0; $i < 8; $i++) $aParams[] = "%$search%";
    }
    if ($selectedBranch !== '') { $aWhere[] = "c.branch = ?"; $aParams[] = $selectedBranch; }
    if ($selectedBrand  !== '') { $aWhere[] = "c.brand = ?";  $aParams[] = $selectedBrand; }
    if ($dateFrom       !== '') { $aWhere[] = "cn.started_at >= ?"; $aParams[] = $dateFrom . ' 00:00:00'; }
    if ($dateTo         !== '') { $aWhere[] = "cn.started_at <= ?"; $aParams[] = $dateTo   . ' 23:59:59'; }

    $aSql = "
        SELECT c.*, cn.dealer_name, cn.salesman, cn.started_at
        FROM cars c
        LEFT JOIN consignments cn ON cn.car_id = c.id AND cn.status = 'active'
        WHERE " . implode(' AND ', $aWhere) . "
        ORDER BY c.branch, c.brand, c.model, c.trim_name
    ";
    // Same as above: every consignment car is sent, the filters apply live.
    $aSql = "
        SELECT c.*, cn.dealer_name, cn.salesman, cn.started_at
        FROM cars c
        LEFT JOIN consignments cn ON cn.car_id = c.id AND cn.status = 'active'
        WHERE c.status = 'consignment'
        ORDER BY c.branch, c.brand, c.model, c.trim_name
    ";
    $amanaCars = $pdo->query($aSql)->fetchAll(PDO::FETCH_ASSOC);
}

/* ─── Look-ups done once for the whole page ───
   The tables below used to query the colour for every single row and the
   branch name and count for every branch. The same answers are read once
   here instead, so the page stays fast as stock grows. Output is identical. */
$colorMap = [];
foreach ($pdo->query("SELECT color_en, color_ar FROM colors")->fetchAll(PDO::FETCH_ASSOC) as $c) {
    if (!isset($colorMap[$c['color_en']])) $colorMap[$c['color_en']] = $c;
}
$branchMap = [];
foreach ($branches as $b) $branchMap[$b['name']] = $b;

$colorLabel  = function ($en) use ($colorMap, $lang) {
    $c = $colorMap[$en] ?? null;
    return $c ? (($lang === 'ar' ? $c['color_ar'] : $c['color_en']) ?: $en) : $en;
};
$branchLabel = function ($name) use ($branchMap, $lang) {
    $b = $branchMap[$name] ?? null;
    return $b ? (($lang === 'ar' ? $b['name_ar'] : $b['name_en']) ?: $name) : $name;
};
// cars per branch within the current filters (same number the old per-branch query returned)
$branchCounts = array_count_values(array_map(fn($c) => (string)$c['branch'], $cars));

/* ─── Everything the pop-up car card shows, keyed by car id ─── */
$imgMap   = car_images_map($pdo);
$cardData = [];
$daysIn   = function ($dt) {
    if (empty($dt)) return null;
    $ts = strtotime($dt);
    return $ts ? max(0, (int)floor((time() - $ts) / 86400)) : null;
};
$addCard  = function (array $car, string $status) use (&$cardData, $imgMap, $colorLabel, $branchLabel, $daysIn) {
    $cardData[(int)$car['id']] = [
        'id'       => (int)$car['id'],
        'brand'    => (string)$car['brand'],
        'model'    => (string)$car['model'],
        'trim'     => (string)$car['trim_name'],
        'year'     => (string)$car['car_year'],
        'color'    => $colorLabel((string)$car['color']),
        'colorEn'  => (string)$car['color'],
        'branch'   => $branchLabel((string)$car['branch']),
        'chassis'  => (string)$car['chassis'],
        'notes'    => trim((string)($car['notes'] ?? '')),
        'by'       => (string)($car['created_by'] ?? ''),
        'arrived'  => !empty($car['created_at']) ? date('Y-m-d', strtotime($car['created_at'])) : '',
        'days'     => $daysIn($car['created_at'] ?? null),
        'status'   => $status,
        'dealer'   => (string)($car['dealer_name'] ?? ''),
        'since'    => !empty($car['started_at']) ? date('Y-m-d', strtotime($car['started_at'])) : '',
        'img'      => car_image_url_for($imgMap, $car, true),
    ];
};
foreach ($cars as $c)      $addCard($c, ($c['status'] ?? '') === 'reserved' ? 'reserved' : 'available');
foreach ($amanaCars as $c) $addCard($c, 'consignment');

$canEditCar = can('page.edit_vehicle');

/** A display swatch for a colour name; unknown names fall back to neutral grey. */
function sr_swatch(string $colorEn): string
{
    static $map = [
        'white' => '#f8fafc', 'pearl white' => '#f1f5f9', 'black' => '#111827', 'silver' => '#cbd5e1',
        'grey' => '#6b7280', 'gray' => '#6b7280', 'red' => '#dc2626', 'blue' => '#2563eb', 'navy' => '#1e3a8a',
        'green' => '#16a34a', 'gold' => '#d4af37', 'beige' => '#e0d5c0', 'brown' => '#78350f',
        'orange' => '#ea580c', 'yellow' => '#eab308', 'purple' => '#7c3aed', 'bronze' => '#a97142', 'champagne' => '#e6d7b8',
    ];
    return $map[mb_strtolower(trim($colorEn))] ?? '#64748b';
}

/* What each row carries for the live filter, the hover preview and the badges.
   The searchable text covers the same fields the old SQL search did, plus the
   Arabic colour and branch names so searching in Arabic works too. */
$rowAttrs = function (array $car, string $kind) use ($cardData, $colorLabel, $branchLabel): string {
    $fields = [$car['brand'], $car['model'], $car['trim_name'], $car['car_year'], $car['color'],
               $car['chassis'], $car['branch'], $colorLabel((string)$car['color']), $branchLabel((string)$car['branch'])];
    $fields[] = $kind === 'amana' ? ($car['dealer_name'] ?? '') : ($car['notes'] ?? '');
    $cd   = $cardData[(int)$car['id']] ?? [];
    $date = $kind === 'amana' ? ($car['started_at'] ?? '') : ($car['created_at'] ?? '');
    return ' data-branch="' . htmlspecialchars((string)$car['branch'], ENT_QUOTES) . '"'
         . ' data-brand="'  . htmlspecialchars((string)$car['brand'], ENT_QUOTES) . '"'
         . ' data-date="'   . htmlspecialchars((string)$date, ENT_QUOTES) . '"'
         . ' data-age="'    . (isset($cd['days']) && $cd['days'] !== null ? (int)$cd['days'] : '') . '"'
         . ' data-sw="'     . sr_swatch((string)$car['color']) . '"'
         . ' data-cl="'     . htmlspecialchars($colorLabel((string)$car['color']), ENT_QUOTES) . '"'
         . ' data-img="'    . htmlspecialchars((string)($cd['img'] ?? ''), ENT_QUOTES) . '"'
         . ' data-search="' . htmlspecialchars(mb_strtolower(implode(' ', array_map('strval', $fields))), ENT_QUOTES) . '"';
};
$agePill = function (array $car) use ($cardData): string {
    $d = $cardData[(int)$car['id']]['days'] ?? null;
    if ($d === null) return '';
    $cls = $d < 30 ? 'g' : ($d < 90 ? 'a' : 'r');
    return '<span class="age-pill ' . $cls . ' scr">' . $d . '</span>';
};
$canQrCard  = can('qr.manage');

/* ─── Auto-trigger print dialog when ?print=1 ─── */
$autoPrint = isset($_GET['print']) && $_GET['print'] === '1';

?>
<!DOCTYPE html>
<html lang="<?= $lang ?>" dir="<?= $dir ?>">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?= $t[$lang]['title'] ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;900&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">

<style>
*, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }

:root {
    --bg-deep:      #020617;
    --bg-surface:   #0b1221;
    --bg-card:      rgba(15,23,42,.92);
    --border:       rgba(255,255,255,.07);
    --green:        #22c55e;
    --green-dim:    rgba(34,197,94,.12);
    --purple:       #9333ea;
    --purple-dim:   rgba(147,51,234,.12);
    --blue:         #2563eb;
    --amber:        #f59e0b;
    --amber-dim:    rgba(245,158,11,.10);
    --text:         #f1f5f9;
    --muted:        #64748b;
    --muted-light:  #94a3b8;
    --radius-card:  20px;
    --radius-btn:   12px;
    --radius-input: 12px;
    --font-ar:      'Cairo', sans-serif;
    --font-en:      'Inter', sans-serif;
    --shadow:       0 4px 24px rgba(0,0,0,.4);
}

html[lang="ar"] body { font-family: var(--font-ar); }
html[lang="en"] body { font-family: var(--font-en); }

body {
    background: linear-gradient(150deg, #020617 0%, #0a0f1e 50%, #05101f 100%);
    color: var(--text);
    min-height: 100vh;
    padding-bottom: 80px;
}

.wrap { max-width: 1600px; margin: auto; padding: 16px 20px; }

.quote-banner {
    background: linear-gradient(90deg, rgba(34,197,94,.08) 0%, rgba(147,51,234,.10) 100%);
    border: 1px solid rgba(34,197,94,.18);
    border-radius: var(--radius-card);
    padding: 14px 22px;
    display: flex;
    align-items: center;
    gap: 14px;
    margin-bottom: 18px;
    position: relative;
    overflow: hidden;
}
.quote-banner::before {
    content: '';
    position: absolute;
    inset: 0;
    background: radial-gradient(ellipse at 0% 50%, rgba(34,197,94,.06), transparent 60%);
    pointer-events: none;
}
.quote-icon { font-size: 26px; flex-shrink: 0; }
.quote-text { font-size: 13.5px; color: #cbd5e1; line-height: 1.65; }
.quote-author { font-size: 12px; color: var(--green); font-weight: 700; margin-top: 4px; }

.header {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    padding: 20px 24px;
    margin-bottom: 18px;
    backdrop-filter: blur(20px);
    box-shadow: var(--shadow);
}
.header-top {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 16px;
    flex-wrap: wrap;
}
.page-title {
    font-size: 28px;
    font-weight: 900;
    background: linear-gradient(90deg, var(--green), #86efac);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    line-height: 1.2;
}
.page-subtitle { font-size: 13px; color: var(--muted-light); margin-top: 4px; }

.nav-group { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }

.nav-btn {
    text-decoration: none;
    padding: 9px 16px;
    border-radius: var(--radius-btn);
    font-weight: 700;
    font-size: 13px;
    color: white;
    transition: transform .2s, box-shadow .2s;
    display: flex;
    align-items: center;
    gap: 6px;
}
.nav-btn:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,.35); }
.nav-btn.dash   { background: var(--blue); }
.nav-btn.inv    { background: var(--green); color: #002b14; }
.nav-btn.report { background: var(--purple); }

.lang-row { display: flex; gap: 8px; margin-top: 14px; }
.lang-btn {
    text-decoration: none;
    padding: 7px 14px;
    border-radius: 10px;
    background: #111827;
    color: var(--muted-light);
    font-size: 12px;
    font-weight: 700;
    border: 1px solid var(--border);
    transition: background .2s;
}
.lang-btn.active { background: var(--purple); color: white; border-color: transparent; }

.stats-row {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 14px;
    margin-bottom: 18px;
}
.stat-card {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    padding: 22px 18px;
    text-align: center;
    position: relative;
    overflow: hidden;
    box-shadow: var(--shadow);
}
.stat-card::after {
    content: '';
    position: absolute;
    bottom: 0; left: 0; right: 0;
    height: 3px;
}
.stat-card.c-total::after  { background: linear-gradient(90deg, var(--green), #86efac); }
.stat-card.c-branch::after { background: linear-gradient(90deg, var(--blue), #60a5fa); }
.stat-card.c-brand::after  { background: linear-gradient(90deg, var(--purple), #c084fc); }

.stat-label { font-size: 12px; text-transform: uppercase; letter-spacing: .06em; color: var(--muted); font-weight: 700; }
.stat-number { font-size: 48px; font-weight: 900; margin-top: 6px; line-height: 1; }
.c-total  .stat-number { color: var(--green); }
.c-branch .stat-number { color: #60a5fa; }
.c-brand  .stat-number { color: #c084fc; }

.filters-card {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    padding: 20px 22px;
    margin-bottom: 18px;
    box-shadow: var(--shadow);
}
.filter-grid {
    display: grid;
    grid-template-columns: 2fr 1fr 1fr 1fr 1fr auto auto;
    gap: 10px;
    align-items: end;
}
.filter-group { display: flex; flex-direction: column; gap: 5px; }
.filter-label { font-size: 11px; font-weight: 700; color: var(--muted); text-transform: uppercase; letter-spacing: .05em; }

input[type="text"],
input[type="date"],
select {
    width: 100%;
    height: 48px;
    border: 1px solid rgba(255,255,255,.08);
    outline: none;
    background: #0d1526;
    color: var(--text);
    padding: 0 14px;
    border-radius: var(--radius-input);
    font-size: 14px;
    transition: border-color .2s, box-shadow .2s;
    font-family: inherit;
    -webkit-appearance: none;
    appearance: none;
}
input:focus, select:focus {
    border-color: var(--green);
    box-shadow: 0 0 0 3px rgba(34,197,94,.12);
}
select { cursor: pointer; }
select option { background: #0d1526; }

input[type="date"]::-webkit-calendar-picker-indicator { filter: invert(1) opacity(.5); cursor: pointer; }

.btn-search {
    height: 48px;
    padding: 0 22px;
    border: none;
    border-radius: var(--radius-btn);
    font-weight: 800;
    font-size: 14px;
    cursor: pointer;
    background: linear-gradient(90deg, var(--green), #16a34a);
    color: #002b14;
    font-family: inherit;
    transition: transform .2s, box-shadow .2s;
    white-space: nowrap;
}
.btn-search:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(34,197,94,.3); }

.btn-reset {
    height: 48px;
    padding: 0 18px;
    border: 1px solid var(--border);
    border-radius: var(--radius-btn);
    font-weight: 700;
    font-size: 13px;
    cursor: pointer;
    background: #111827;
    color: var(--muted-light);
    text-decoration: none;
    display: flex;
    align-items: center;
    gap: 6px;
    font-family: inherit;
    transition: border-color .2s;
    white-space: nowrap;
}
.btn-reset:hover { border-color: var(--muted); }

.table-card {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    padding: 24px;
    box-shadow: var(--shadow);
}

.branch-section { margin-bottom: 36px; }

.branch-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 12px;
    padding-bottom: 12px;
    border-bottom: 1px solid rgba(255,255,255,.06);
    gap: 10px;
    flex-wrap: wrap;
}
.branch-title {
    font-size: 18px;
    font-weight: 800;
    color: var(--green);
    display: flex;
    align-items: center;
    gap: 8px;
}
.branch-badge {
    background: var(--green-dim);
    color: var(--green);
    padding: 5px 14px;
    border-radius: 50px;
    font-size: 12px;
    font-weight: 800;
    border: 1px solid rgba(34,197,94,.2);
}

.inv-table { width: 100%; border-collapse: collapse; }
.inv-table thead tr { background: #0d1526; }
.inv-table th {
    padding: 12px 14px;
    text-align: center;
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: .05em;
    color: var(--muted);
    white-space: nowrap;
}
.inv-table td {
    padding: 11px 14px;
    text-align: center;
    border-bottom: 1px solid rgba(255,255,255,.04);
    font-size: 13.5px;
}
.inv-table tr:last-child td { border-bottom: none; }
.inv-table tbody tr { transition: background .15s; }
.inv-table tbody tr:hover { background: rgba(34,197,94,.04); }

/* ── 🔒 محجوزة / Reserved — golden row ── */
.inv-table tbody tr.res-row {
    background: linear-gradient(90deg, rgba(250,204,21,.10), rgba(234,179,8,.04));
    box-shadow: inset 3px 0 0 #facc15;
}
.inv-table tbody tr.res-row:hover { background: rgba(250,204,21,.16); }
.inv-table tbody tr.res-row td { color: #fde68a; }
.res-badge {
    display: inline-block; font-size: 10px; font-weight: 800;
    padding: 2px 8px; border-radius: 20px; white-space: nowrap;
    background: rgba(250,204,21,.18); color: #facc15;
    border: 1px solid rgba(250,204,21,.45);
}

.num-cell { color: var(--muted); font-size: 12px; }
.chassis-cell { font-family: 'Courier New', monospace; font-size: 12px; color: var(--muted-light); letter-spacing: .04em; }
.brand-cell { font-weight: 700; color: #e2e8f0; }

.notes-cell {
    font-size: 12.5px;
    color: var(--muted);
    text-align: start;
    max-width: 220px;
    white-space: normal;
    word-break: break-word;
}
.notes-cell.has-note {
    color: #fcd34d;
    font-weight: 600;
}

.empty-state {
    text-align: center;
    padding: 60px 20px;
    color: var(--muted);
}
.empty-state .e-icon { font-size: 48px; margin-bottom: 12px; }
.empty-state p { font-size: 16px; }

.actions-bar {
    display: flex;
    gap: 12px;
    justify-content: center;
    margin-top: 24px;
    flex-wrap: wrap;
}
.act-btn {
    text-decoration: none;
    border: none;
    cursor: pointer;
    padding: 13px 26px;
    border-radius: var(--radius-btn);
    font-size: 14px;
    font-weight: 800;
    color: white;
    display: flex;
    align-items: center;
    gap: 8px;
    font-family: inherit;
    transition: transform .2s, box-shadow .2s;
}
.act-btn:hover { transform: translateY(-2px); }
.act-print { background: var(--green); color: #002b14; }
.act-print:hover { box-shadow: 0 6px 20px rgba(34,197,94,.3); }

.report-footer {
    margin-top: 20px;
    padding: 16px 22px;
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-card);
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 10px;
    font-size: 13px;
    color: var(--muted-light);
}
.report-footer strong { color: var(--text); }

.grand-card {
    margin-top: 20px;
    background: linear-gradient(135deg, rgba(34,197,94,.15) 0%, rgba(147,51,234,.15) 100%);
    border: 1px solid rgba(34,197,94,.25);
    border-radius: var(--radius-card);
    padding: 28px;
    text-align: center;
}
.grand-label { font-size: 15px; font-weight: 700; color: var(--muted-light); }

/* ── امانة report block (amber) ── */
.amana-report-card { margin-top: 22px; }
.amana-report-header { background: rgba(245,158,11,.1) !important; border-color: rgba(245,158,11,.3) !important; }
.amana-report-badge { background: rgba(245,158,11,.2) !important; color: #f59e0b !important; }
.amana-dealer-cell { color: #b45309; font-weight: 700; }
.amana-grand-card {
    background: linear-gradient(135deg, rgba(245,158,11,.15) 0%, rgba(249,115,22,.15) 100%) !important;
    border: 1px solid rgba(245,158,11,.3) !important;
}
.amana-grand-card .grand-number {
    background: linear-gradient(90deg, #f59e0b, #f97316) !important;
    -webkit-background-clip: text; background-clip: text;
}
@media print {
    .amana-report-header { background: #fdf0d5 !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .amana-dealer-cell { color: #92400e !important; }
}
.grand-number {
    font-size: 72px;
    font-weight: 900;
    line-height: 1;
    margin-top: 8px;
    background: linear-gradient(90deg, var(--green), var(--purple));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

@media (max-width: 1100px) {
    .filter-grid { grid-template-columns: 1fr 1fr; }
}
@media (max-width: 700px) {
    .stats-row { grid-template-columns: 1fr; }
    .filter-grid { grid-template-columns: 1fr; }
    .header-top { flex-direction: column; align-items: flex-start; }
    .stat-number { font-size: 38px; }
    .grand-number { font-size: 52px; }
    .inv-table { display: block; overflow-x: auto; white-space: nowrap; }
    .page-title { font-size: 22px; }
    .notes-cell { max-width: none; white-space: nowrap; }
}

/* ═══════════════════════════════════════
   PRINT — COMPACT, FIT ON ONE PAGE
═══════════════════════════════════════ */
@media print {
    @page { size: A4 landscape; margin: 6mm 6mm; }

    html, body {
        background: white !important;
        color: black !important;
        font-size: 7px !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
    }

    .quote-banner,
    .header .nav-group,
    .lang-row,
    .filters-card,
    .actions-bar,
    .report-footer { display: none !important; }

    .wrap { padding: 0 !important; max-width: 100% !important; }

    .header {
        background: white !important;
        border: none !important;
        box-shadow: none !important;
        padding: 0 0 4px 0 !important;
        margin-bottom: 4px !important;
    }
    .page-title {
        font-size: 13px !important;
        -webkit-text-fill-color: #1a1a1a !important;
        color: #1a1a1a !important;
        background: none !important;
        margin: 0 !important;
    }
    .page-subtitle { color: #555 !important; font-size: 8px !important; }

    .stats-row {
        gap: 4px !important;
        margin-bottom: 5px !important;
        grid-template-columns: repeat(3, 1fr) !important;
    }
    .stat-card {
        background: #f5f5f5 !important;
        border: 1px solid #ddd !important;
        padding: 3px 6px !important;
        box-shadow: none !important;
        border-radius: 6px !important;
    }
    .stat-card::after { display: none !important; }
    .stat-label { color: #555 !important; font-size: 7px !important; }
    .stat-number { font-size: 14px !important; margin-top: 1px !important; }
    .c-total  .stat-number { color: #16a34a !important; }
    .c-branch .stat-number { color: #1d4ed8 !important; }
    .c-brand  .stat-number { color: #7e22ce !important; }

    .table-card {
        background: white !important;
        border: none !important;
        box-shadow: none !important;
        padding: 0 !important;
    }

    .branch-section {
        page-break-inside: auto;
        margin-bottom: 6px !important;
    }
    .branch-header {
        padding-bottom: 3px !important;
        margin-bottom: 3px !important;
        border-bottom: 1px solid #ccc !important;
    }
    .branch-title { color: #15803d !important; font-size: 9px !important; gap: 4px !important; }
    .branch-badge {
        background: #dcfce7 !important;
        color: #15803d !important;
        border: 1px solid #86efac !important;
        font-size: 7px !important;
        padding: 1px 7px !important;
    }

    .inv-table { width: 100% !important; }
    .inv-table th {
        background: #1e293b !important;
        color: white !important;
        font-size: 7px !important;
        padding: 2px 4px !important;
        letter-spacing: 0 !important;
    }
    .inv-table td {
        font-size: 7px !important;
        padding: 1.5px 4px !important;
        color: black !important;
        border-bottom: 1px solid #e5e7eb !important;
        line-height: 1.2 !important;
    }
    .inv-table tbody tr { page-break-inside: avoid !important; }
    .chassis-cell { color: #374151 !important; font-size: 6.5px !important; }
    .brand-cell   { color: black !important; }
    .notes-cell, .notes-cell.has-note {
        color: #92400e !important;
        font-weight: 600 !important;
        max-width: 140px !important;
        white-space: normal !important;
    }

    .grand-card {
        background: white !important;
        border: 1.5px solid #000 !important;
        padding: 6px !important;
        margin-top: 6px !important;
        border-radius: 6px !important;
        page-break-inside: avoid !important;
    }
    .grand-label { color: #333 !important; font-size: 9px !important; }
    .grand-number {
        -webkit-text-fill-color: #111 !important;
        background: none !important;
        color: #111 !important;
        font-size: 22px !important;
        margin-top: 2px !important;
    }
}
</style>
</head>
<body>
<div class="wrap">

    <!-- ── QUOTE BANNER ──────────────────────────────── -->
    <div class="quote-banner">
        <span class="quote-icon">💬</span>
        <div>
            <div class="quote-text">«<?= htmlspecialchars($quote['text']) ?>»</div>
            <div class="quote-author">— <?= htmlspecialchars($quote['author']) ?></div>
        </div>
    </div>

    <!-- ── HEADER ────────────────────────────────────── -->
    <div class="header">
        <div class="header-top">
            <div>
                <div class="page-title">📄 <?= $t[$lang]['title'] ?></div>
                <div class="page-subtitle"><?= $t[$lang]['subtitle'] ?></div>
            </div>
            <div class="nav-group">
                <a href="dashboard.php?lang=<?= $lang ?>"  class="nav-btn dash">🏠 <?= $t[$lang]['dashboard'] ?></a>
                <a href="stock_report.php?lang=<?= $lang ?>" class="nav-btn report">📄 <?= $t[$lang]['title'] ?></a>
            </div>
        </div>
        <div class="lang-row">
            <a href="?lang=ar&search=<?= urlencode($search) ?>&branch=<?= urlencode($selectedBranch) ?>&brand=<?= urlencode($selectedBrand) ?>&date_from=<?= urlencode($dateFrom) ?>&date_to=<?= urlencode($dateTo) ?>"
               class="lang-btn <?= $lang === 'ar' ? 'active' : '' ?>">🇪🇬 العربية</a>
            <a href="?lang=en&search=<?= urlencode($search) ?>&branch=<?= urlencode($selectedBranch) ?>&brand=<?= urlencode($selectedBrand) ?>&date_from=<?= urlencode($dateFrom) ?>&date_to=<?= urlencode($dateTo) ?>"
               class="lang-btn <?= $lang === 'en' ? 'active' : '' ?>">🇺🇸 English</a>
        </div>
    </div>

    <!-- ── STATS ─────────────────────────────────────── -->
    <div class="kpi-row scr" id="kpiRow">
        <div class="kpi k-total"><div class="kpi-n" data-k="total">0</div><div class="kpi-l">🚗 <?= $t[$lang]['available_only'] ?></div></div>
        <div class="kpi k-av"><div class="kpi-n" data-k="av">0</div><div class="kpi-l">✅ <?= $lang === 'ar' ? 'متاحة' : 'Available' ?></div></div>
        <div class="kpi k-res"><div class="kpi-n" data-k="res">0</div><div class="kpi-l">🔒 <?= $t[$lang]['reserved'] ?></div></div>
        <?php if ($canSeeAmana && !empty($amanaCars)): ?>
        <div class="kpi k-am"><div class="kpi-n" data-k="am">0</div><div class="kpi-l">🔶 <?= $lang === 'ar' ? 'أمانة' : 'Consignment' ?></div></div>
        <?php endif; ?>
        <div class="kpi k-age"><div class="kpi-n" data-k="age">0</div><div class="kpi-l">⏱ <?= $lang === 'ar' ? 'متوسط الأيام في المخزون' : 'Average days in stock' ?></div></div>
    </div>

    <div class="stats-row prn">
        <div class="stat-card c-total">
            <div class="stat-label"><?= $t[$lang]['total_cars'] ?></div>
            <div class="stat-number"><?= $totalCars ?></div>
        </div>
        <div class="stat-card c-branch">
            <div class="stat-label"><?= $t[$lang]['branches'] ?></div>
            <div class="stat-number"><?= $branchCount ?></div>
        </div>
        <div class="stat-card c-brand">
            <div class="stat-label"><?= $t[$lang]['brands'] ?></div>
            <div class="stat-number"><?= $brandCount ?></div>
        </div>
    </div>

    <!-- ── FILTERS ───────────────────────────────────── -->
    <form method="GET" class="filters-card">
        <input type="hidden" name="lang" value="<?= $lang ?>">
        <div class="filter-grid">

            <div class="filter-group">
                <span class="filter-label">🔍 <?= $t[$lang]['search'] ?></span>
                <input type="text" name="search"
                       placeholder="<?= $t[$lang]['search'] ?>"
                       value="<?= htmlspecialchars($search) ?>">
            </div>

            <div class="filter-group">
                <span class="filter-label">📍 <?= $t[$lang]['branch'] ?></span>
                <select name="branch">
                    <option value=""><?= $t[$lang]['all_branches'] ?></option>
                    <?php foreach ($branches as $b): ?>
                    <option value="<?= htmlspecialchars($b['name']) ?>"
                        <?= $selectedBranch === $b['name'] ? 'selected' : '' ?>>
                        <?= htmlspecialchars($lang === 'ar' ? $b['name_ar'] : $b['name_en']) ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="filter-group">
                <span class="filter-label">🚘 <?= $t[$lang]['brand'] ?></span>
                <select name="brand">
                    <option value=""><?= $t[$lang]['all_brands'] ?></option>
                    <?php foreach ($brands as $b): ?>
                    <option value="<?= htmlspecialchars($b['brand']) ?>"
                        <?= $selectedBrand === $b['brand'] ? 'selected' : '' ?>>
                        <?= htmlspecialchars($b['brand']) ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="filter-group">
                <span class="filter-label">📅 <?= $t[$lang]['date_from'] ?></span>
                <input type="date" name="date_from" value="<?= htmlspecialchars($dateFrom) ?>">
            </div>

            <div class="filter-group">
                <span class="filter-label">📅 <?= $t[$lang]['date_to'] ?></span>
                <input type="date" name="date_to" value="<?= htmlspecialchars($dateTo) ?>">
            </div>

            <button type="submit" class="btn-search">🔍 <?= $t[$lang]['search_btn'] ?></button>

            <a href="stock_report.php?lang=<?= $lang ?>" class="btn-reset">✕ <?= $t[$lang]['reset'] ?></a>
        </div>
    </form>

    <!-- ── Branch jump bar: tap to glide to a branch; it lights up as you scroll ── -->
    <nav class="jumpbar scr" id="jumpBar" aria-label="branches"></nav>

    <!-- ── TABLE ─────────────────────────────────────── -->
    <div class="table-card">
        <?php if (count($cars) === 0): ?>
        <div class="empty-state">
            <div class="e-icon">🚗</div>
            <p><?= $t[$lang]['no_cars'] ?></p>
        </div>
        <?php else:
            $currentBranch = '';
            $counter = 1;
            foreach ($cars as $car):
                if ($currentBranch !== $car['branch']):
                    if ($currentBranch !== '') { echo '</tbody></table></div>'; }
                    $currentBranch = $car['branch'];

                    $bDisplay    = $branchLabel((string)$currentBranch);
                    $branchTotal = $branchCounts[(string)$currentBranch] ?? 0;

                    $counter = 1;
        ?>
                    <div class="branch-section" data-branch="<?= htmlspecialchars((string)$currentBranch, ENT_QUOTES) ?>" data-label="<?= htmlspecialchars($bDisplay, ENT_QUOTES) ?>">
                    <div class="branch-header">
                        <span class="bh-ring scr"></span>
                        <div class="branch-title">📍 <?= htmlspecialchars($bDisplay) ?></div>
                        <span class="bh-dots scr"></span>
                        <div class="branch-badge"><span class="bb-n"><?= $branchTotal ?></span> <?= $t[$lang]['cars_count'] ?></div>
                        <button type="button" class="bh-fold scr" aria-label="fold">▾</button>
                    </div>
                    <table class="inv-table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><?= $t[$lang]['brand'] ?></th>
                                <th><?= $t[$lang]['model'] ?></th>
                                <th><?= $t[$lang]['trim'] ?></th>
                                <th><?= $t[$lang]['year'] ?></th>
                                <th><?= $t[$lang]['color'] ?></th>
                                <th><?= $t[$lang]['chassis'] ?></th>
                                <th><?= $t[$lang]['notes'] ?></th>
                            </tr>
                        </thead>
                        <tbody>
        <?php endif; ?>
                        <?php
                            $noteText   = trim((string)($car['notes'] ?? ''));
                            $isReserved = (($car['status'] ?? '') === 'reserved');
                        ?>
                        <tr class="car-row <?= $isReserved ? 'res-row' : '' ?>" data-id="<?= (int)$car['id'] ?>" tabindex="0"<?= $rowAttrs($car, 'stock') ?>>
                            <td class="num-cell"><?= $counter++ ?></td>
                            <td class="brand-cell">
                                <?php if ($isReserved): ?><span class="res-badge">🔒 <?= $t[$lang]['reserved'] ?></span> <?php endif; ?>
                                <?= htmlspecialchars($car['brand']) ?>
                            </td>
                            <td><?= htmlspecialchars($car['model']) ?></td>
                            <td><?= htmlspecialchars($car['trim_name']) ?></td>
                            <td><?= htmlspecialchars($car['car_year']) ?></td>
                            <td>
                            <i class="sw scr" style="background:<?= sr_swatch((string)$car['color']) ?>"></i><?= htmlspecialchars($colorLabel((string)$car['color'])) ?>
                            </td>
                            <td class="chassis-cell"><span class="ch-chip"><?= htmlspecialchars($car['chassis']) ?></span><?= $agePill($car) ?></td>
                            <td class="notes-cell <?= $noteText !== '' ? 'has-note' : '' ?>">
                                <?= $noteText !== '' ? '📝 ' . htmlspecialchars($noteText) : '—' ?>
                            </td>
                        </tr>
        <?php endforeach; ?>
                        </tbody>
                    </table>
                    </div>
        <?php endif; ?>
        <div class="empty-state live-empty" style="display:none">
            <div class="e-icon">🚗</div>
            <p><?= $t[$lang]['no_cars'] ?></p>
        </div>
    </div><!-- /.table-card -->

    <?php if ($canSeeAmana && !empty($amanaCars)): ?>
    <!-- ── امانة / CONSIGNMENT (admin/manager only) ─────── -->
    <div class="table-card amana-report-card">
        <div class="branch-section" data-branch="__amana__" data-label="<?= htmlspecialchars(strip_tags($t[$lang]['amana_section']), ENT_QUOTES) ?>">
            <div class="branch-header amana-report-header">
                <span class="bh-ring scr"></span>
                <div class="branch-title"><?= $t[$lang]['amana_section'] ?></div>
                <span class="bh-dots scr"></span>
                <div class="branch-badge amana-report-badge"><span class="bb-n"><?= count($amanaCars) ?></span> <?= $t[$lang]['cars_count'] ?></div>
                <button type="button" class="bh-fold scr" aria-label="fold">▾</button>
            </div>
            <table class="inv-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th><?= $t[$lang]['brand'] ?></th>
                        <th><?= $t[$lang]['model'] ?></th>
                        <th><?= $t[$lang]['trim'] ?></th>
                        <th><?= $t[$lang]['year'] ?></th>
                        <th><?= $t[$lang]['color'] ?></th>
                        <th><?= $t[$lang]['chassis'] ?></th>
                        <th><?= $t[$lang]['branch'] ?></th>
                        <th><?= $t[$lang]['amana_dealer'] ?></th>
                        <th><?= $t[$lang]['amana_since'] ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $ac = 1; foreach ($amanaCars as $car):
                        $cDisplay = $colorLabel((string)$car['color']);
                        $bDisplay = $branchLabel((string)$car['branch']);

                        $sinceFmt = !empty($car['started_at']) ? date('Y-m-d', strtotime($car['started_at'])) : '—';
                    ?>
                    <tr class="car-row" data-id="<?= (int)$car['id'] ?>" tabindex="0"<?= $rowAttrs($car, 'amana') ?>>
                        <td class="num-cell"><?= $ac++ ?></td>
                        <td class="brand-cell"><?= htmlspecialchars($car['brand']) ?></td>
                        <td><?= htmlspecialchars($car['model']) ?></td>
                        <td><?= htmlspecialchars($car['trim_name']) ?></td>
                        <td><?= htmlspecialchars($car['car_year']) ?></td>
                        <td><i class="sw scr" style="background:<?= sr_swatch((string)$car['color']) ?>"></i><?= htmlspecialchars($cDisplay) ?></td>
                        <td class="chassis-cell"><span class="ch-chip"><?= htmlspecialchars($car['chassis']) ?></span><?= $agePill($car) ?></td>
                        <td><?= htmlspecialchars($bDisplay) ?></td>
                        <td class="amana-dealer-cell"><?= htmlspecialchars($car['dealer_name'] ?? '—') ?></td>
                        <td><?= htmlspecialchars($sinceFmt) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="grand-card amana-grand-card prn">
        <div class="grand-label"><?= $t[$lang]['amana_total'] ?></div>
        <div class="grand-number"><?= count($amanaCars) ?></div>
    </div>
    <?php endif; ?>

    <!-- ── ACTIONS ───────────────────────────────────── -->
    <div class="actions-bar">
        <button type="button" onclick="window.print()" class="act-btn act-print">
            🖨 <?= $t[$lang]['print'] ?>
        </button>
    </div>

    <!-- ── FOOTER ────────────────────────────────────── -->
    <div class="report-footer">
        <div><?= $t[$lang]['generated_by'] ?>: <strong><?= htmlspecialchars($_SESSION['username']) ?></strong></div>
        <div><?= $t[$lang]['generated_at'] ?>: <strong><?= date('d M Y  h:i A') ?></strong></div>
    </div>

    <!-- ── GRAND TOTAL ───────────────────────────────── -->
    <div class="grand-card prn">
        <div class="grand-label">🚗 <?= $t[$lang]['available_only'] ?></div>
        <div class="grand-number"><?= $totalCars ?></div>
    </div>

</div><!-- /.wrap -->

<script>
<?php if ($autoPrint): ?>
    window.addEventListener('load', function () {
        setTimeout(function () { window.print(); }, 400);
    });
<?php endif; ?>
</script>

<!-- ══════════ Screen-only polish. Nothing below changes what prints. ══════════ -->
<style>
@media print { .scr { display:none !important; } }
@media screen {
    .prn { display:none !important; }

    /* ambient light behind the page, like the dashboard */
    body::before {
        content:''; position:fixed; inset:0; z-index:-1; pointer-events:none;
        background:
            radial-gradient(ellipse 55% 40% at 88% -6%, rgba(147,51,234,.16), transparent 70%),
            radial-gradient(ellipse 45% 35% at 6% 2%, rgba(34,197,94,.11), transparent 70%),
            radial-gradient(ellipse 60% 45% at 50% 110%, rgba(59,130,246,.08), transparent 70%);
    }

    /* ── headline numbers ── */
    .kpi-row { display:grid; grid-template-columns:repeat(auto-fit,minmax(165px,1fr)); gap:12px; margin-bottom:18px; }
    .kpi {
        position:relative; overflow:hidden; padding:18px 20px 16px; border-radius:20px;
        background:linear-gradient(160deg, rgba(20,30,52,.95), rgba(10,16,32,.95));
        border:1px solid rgba(255,255,255,.07); box-shadow:0 8px 30px rgba(0,0,0,.4);
    }
    .kpi::before { content:''; position:absolute; inset-inline:0; top:0; height:3px; background:var(--kc); }
    .kpi::after  { content:''; position:absolute; width:140px; height:140px; border-radius:50%; top:-70px; inset-inline-end:-40px;
                   background:radial-gradient(circle, var(--kc) 0%, transparent 70%); opacity:.14; }
    .kpi-n { font-size:40px; font-weight:900; line-height:1; color:var(--kc); font-variant-numeric:tabular-nums; letter-spacing:-.02em; }
    .kpi-l { font-size:12.5px; font-weight:800; color:#94a3b8; margin-top:8px; }
    .k-total { --kc:#e2e8f0; } .k-av { --kc:#22c55e; } .k-res { --kc:#eab308; } .k-am { --kc:#f59e0b; } .k-age { --kc:#38bdf8; }
    .k-total .kpi-n { background:linear-gradient(90deg,#fff,#c4b5fd); -webkit-background-clip:text; background-clip:text; -webkit-text-fill-color:transparent; }

    /* ── branch jump bar, pinned ── */
    .jumpbar {
        position:sticky; top:0; z-index:60; display:flex; gap:8px; align-items:center;
        margin:0 -20px 16px; padding:10px 20px; overflow-x:auto; scrollbar-width:none;
        background:rgba(2,6,23,.9); backdrop-filter:blur(16px); -webkit-backdrop-filter:blur(16px);
        border-bottom:1px solid rgba(255,255,255,.07);
    }
    .jumpbar::-webkit-scrollbar { display:none; }
    .jumpbar:empty { display:none; }
    .jp {
        flex-shrink:0; display:inline-flex; align-items:center; gap:8px; height:36px; padding:0 14px 0 10px;
        border-radius:50px; border:1px solid rgba(255,255,255,.1); background:rgba(255,255,255,.04);
        color:#cbd5e1; font-family:inherit; font-size:13px; font-weight:800; cursor:pointer;
        transition:background .25s, color .25s, border-color .25s, box-shadow .25s, transform .15s;
    }
    .jp:hover { transform:translateY(-1px); color:#fff; }
    .jp i { width:10px; height:10px; border-radius:50%; background:var(--bc); box-shadow:0 0 0 3px color-mix(in srgb, var(--bc) 25%, transparent); }
    .jp b { font-size:11.5px; font-weight:900; padding:2px 8px; border-radius:50px; background:rgba(255,255,255,.08); color:#e2e8f0; }
    .jp.on { color:#fff; border-color:transparent; background:linear-gradient(90deg, color-mix(in srgb, var(--bc) 85%, #000), var(--bc)); box-shadow:0 6px 20px color-mix(in srgb, var(--bc) 40%, transparent); }
    .jp.on i { background:#fff; box-shadow:none; }
    .jp.on b { background:rgba(0,0,0,.22); }

    /* ── each branch is its own panel ── */
    .table-card { background:none !important; border:none !important; box-shadow:none !important; padding:0 !important; }
    .branch-section {
        position:relative; margin-bottom:18px !important; padding:0 18px 12px;
        background:linear-gradient(180deg, rgba(15,23,42,.94), rgba(10,16,32,.94));
        border:1px solid rgba(255,255,255,.07); border-radius:22px; box-shadow:0 10px 36px rgba(0,0,0,.4);
        scroll-margin-top:calc(var(--jb-h, 56px) + 10px);
        transition:opacity .6s ease, transform .6s cubic-bezier(.22,1,.36,1);
    }
    .branch-section::before {                 /* branch colour down the leading edge */
        content:''; position:absolute; top:18px; bottom:18px; inset-inline-start:0; width:3px; border-radius:3px;
        background:linear-gradient(180deg, var(--bc,#22c55e), transparent);
    }
    .branch-section.rv-wait { opacity:0; transform:translateY(22px); }

    .branch-header {
        position:sticky; top:var(--jb-h, 56px); z-index:40;
        margin:0 -18px 10px !important; padding:14px 18px !important;
        justify-content:flex-start !important; gap:12px !important;
        background:linear-gradient(90deg, color-mix(in srgb, var(--bc,#22c55e) 13%, #0c1426), #0c1426 70%) !important;
        border-bottom:1px solid rgba(255,255,255,.07) !important; border-radius:22px 22px 0 0;
        backdrop-filter:blur(14px);
    }
    .amana-report-header { background:linear-gradient(90deg, rgba(245,158,11,.18), #0c1426 70%) !important; }
    .branch-section.folded .branch-header { border-radius:22px; border-bottom-color:transparent !important; margin-bottom:0 !important; }
    .branch-section.folded { padding-bottom:0; }
    .branch-section.folded .inv-table { display:none !important; }
    .branch-title { font-size:20px !important; }
    .branch-badge { margin-inline-start:auto; font-size:13px !important; }

    .bh-ring { position:relative; width:46px; height:46px; flex-shrink:0; }
    .bh-ring svg { transform:rotate(-90deg); display:block; }
    .bh-ring .bg { stroke:rgba(255,255,255,.08); }
    .bh-ring .fg { stroke:var(--bc,#22c55e); stroke-linecap:round; transition:stroke-dashoffset 1.1s cubic-bezier(.22,1,.36,1); }
    .bh-ring em { position:absolute; inset:0; display:flex; align-items:center; justify-content:center; font-style:normal; font-size:11px; font-weight:900; color:#e2e8f0; }
    .bh-dots { display:flex; gap:5px; align-items:center; flex-wrap:wrap; }
    .bh-dots span { display:inline-flex; align-items:center; gap:4px; height:24px; padding:0 8px 0 4px; border-radius:50px; background:rgba(255,255,255,.05); border:1px solid rgba(255,255,255,.07); font-size:11px; font-weight:900; color:#cbd5e1; }
    .bh-dots span i { width:14px; height:14px; border-radius:50%; border:1px solid rgba(255,255,255,.3); }
    .bh-fold { width:34px; height:34px; border-radius:11px; border:1px solid rgba(255,255,255,.12); background:rgba(255,255,255,.05); color:#cbd5e1; cursor:pointer; font-size:14px; flex-shrink:0; transition:transform .3s, background .2s; }
    .bh-fold:hover { background:rgba(255,255,255,.1); }
    .branch-section.folded .bh-fold { transform:rotate(-90deg); }
    html[dir="rtl"] .branch-section.folded .bh-fold { transform:rotate(90deg); }

    /* ── the tables: same columns, sharper ── */
    .inv-table thead th { background:#0d1526; }
    .inv-table tbody tr.car-row.zb:not(.res-row) td { background:rgba(255,255,255,.018); }
    .inv-table tbody tr.car-row:hover td { background:rgba(147,51,234,.07) !important; }
    .sw { display:inline-block; width:12px; height:12px; border-radius:50%; border:1px solid rgba(255,255,255,.35); vertical-align:-1px; margin-inline-end:7px; box-shadow:0 0 0 2px rgba(0,0,0,.25); }
    .ch-chip { display:inline-block; font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:12px; letter-spacing:.05em; color:#bef264; background:rgba(163,230,53,.07); border:1px solid rgba(163,230,53,.2); border-radius:8px; padding:3px 8px; }
    .age-pill { display:inline-flex; align-items:center; height:20px; padding:0 7px; margin-inline-start:7px; border-radius:50px; font-size:10.5px; font-weight:900; font-family:inherit; letter-spacing:0; vertical-align:1px; }
    .age-pill::after { content:attr(data-u); margin-inline-start:3px; font-weight:800; opacity:.8; }
    .age-pill.g { background:rgba(34,197,94,.13); color:#4ade80; }
    .age-pill.a { background:rgba(245,158,11,.14); color:#fbbf24; }
    .age-pill.r { background:rgba(239,68,68,.15); color:#f87171; }

    /* reserved rows keep their gold, with a slow light sweeping across */
    .inv-table tbody tr.res-row {
        background-image:linear-gradient(100deg, transparent 35%, rgba(253,224,71,.17) 50%, transparent 65%) !important;
        background-size:250% 100% !important; background-repeat:no-repeat !important;
        animation:resSweep 5s ease-in-out infinite;
    }
    .inv-table tbody tr.res-row td:first-child { box-shadow:inset 3px 0 0 #eab308; }
    html[dir="rtl"] .inv-table tbody tr.res-row td:first-child { box-shadow:inset -3px 0 0 #eab308; }
    @keyframes resSweep { 0% { background-position:130% 0; } 55%,100% { background-position:-130% 0; } }

    /* hover preview of the car photo, on computers only */
    .peek {
        position:fixed; z-index:450; width:230px; height:140px; border-radius:18px; overflow:hidden; pointer-events:none;
        background:radial-gradient(ellipse 85% 60% at 50% 104%, #cbd5e1, transparent 72%), linear-gradient(180deg,#fff,#e2e8f0);
        border:1px solid rgba(255,255,255,.25); box-shadow:0 18px 50px rgba(0,0,0,.6);
        opacity:0; transform:scale(.92) translateY(6px); transition:opacity .18s ease, transform .2s ease;
    }
    .peek.on { opacity:1; transform:none; }
    .peek img { width:100%; height:100%; object-fit:contain; padding:14px 16px; mix-blend-mode:multiply; }
    .peek span { position:absolute; bottom:7px; inset-inline-start:10px; font-size:10.5px; font-weight:900; color:#334155; background:rgba(255,255,255,.8); border-radius:50px; padding:2px 8px; }

    @media (max-width:700px) {
        .jumpbar { margin:0 -20px 14px; padding:9px 14px; }
        .kpi-row { grid-template-columns:repeat(2,1fr); gap:9px; }
        .kpi { padding:14px 14px 12px; border-radius:16px; }
        .kpi-n { font-size:30px; }
        .kpi-l { font-size:11px; }
        .k-total { grid-column:1 / -1; }
        .branch-section { padding:0 10px 10px; border-radius:18px; }
        .branch-header { margin:0 -10px 8px !important; padding:11px 12px !important; border-radius:18px 18px 0 0; flex-wrap:wrap !important; }
        .bh-ring { width:40px; height:40px; }
        .branch-title { font-size:17px !important; }
        .bh-dots { order:5; width:100%; }
    }
    @media (min-width:701px) {
        .inv-table thead th { position:sticky; top:calc(var(--jb-h, 56px) + var(--bh-h, 74px)); z-index:30; }
    }
    @media (prefers-reduced-motion: reduce) {
        .inv-table tbody tr.res-row { animation:none; }
        .branch-section, .bh-ring .fg { transition:none; }
        .branch-section.rv-wait { opacity:1; transform:none; }
    }
}
</style>

<div class="peek scr" id="peek"><img alt=""><span></span></div>

<script>
(function () {
    const AR = <?= json_encode($lang === 'ar') ?>;
    const DAY = AR ? 'يوم' : 'd';
    const PALETTE = ['#22c55e','#8b5cf6','#3b82f6','#f59e0b','#ec4899','#14b8a6','#ef4444','#a3e635','#f97316','#06b6d4'];

    const form     = document.querySelector('.filters-card');
    const stockSec = Array.from(document.querySelectorAll('.table-card:not(.amana-report-card) .branch-section[data-branch]'));
    const amSec    = document.querySelector('.amana-report-card .branch-section');
    const amCard   = document.querySelector('.amana-report-card');
    const amGrand  = document.querySelector('.amana-grand-card');
    const allSec   = stockSec.concat(amSec ? [amSec] : []);
    const empty    = document.querySelector('.live-empty');
    const jump     = document.getElementById('jumpBar');

    // a colour per branch, shared by the ring, the edge, the pills
    stockSec.forEach((sec, i) => sec.style.setProperty('--bc', PALETTE[i % PALETTE.length]));
    if (amSec) amSec.style.setProperty('--bc', '#f59e0b');
    document.querySelectorAll('.age-pill').forEach(p => p.setAttribute('data-u', DAY));

    /* ════ live filter: the same five fields, applied instantly ════ */
    function val(name) { const el = form && form.elements[name]; return el ? String(el.value || '').trim() : ''; }
    function matches(tr, st) {
        if (st.q && (tr.getAttribute('data-search') || '').indexOf(st.q) === -1) return false;
        if (st.branch && tr.getAttribute('data-branch') !== st.branch) return false;
        if (st.brand && tr.getAttribute('data-brand') !== st.brand) return false;
        const d = tr.getAttribute('data-date') || '';
        if (st.from && (!d || d < st.from + ' 00:00:00')) return false;
        if (st.to   && (!d || d > st.to   + ' 23:59:59')) return false;
        return true;
    }
    function runSection(sec, st) {
        let n = 0;
        sec.querySelectorAll('tr.car-row').forEach(tr => {
            const ok = matches(tr, st);
            tr.style.display = ok ? '' : 'none';
            if (ok) {
                n++;
                const num = tr.querySelector('.num-cell'); if (num) num.textContent = n;   // numbering restarts per branch, as before
                tr.classList.toggle('zb', n % 2 === 0);
            }
        });
        const bn = sec.querySelector('.bb-n'); if (bn) bn.textContent = n;
        sec.style.display = n ? '' : 'none';
        sec._n = n;
        return n;
    }

    const shown = { total: 0, av: 0, res: 0, am: 0, age: 0 };
    function apply(silentUrl) {
        const st = { q: val('search').toLowerCase(), branch: val('branch'), brand: val('brand'), from: val('date_from'), to: val('date_to') };
        let total = 0;
        stockSec.forEach(sec => total += runSection(sec, st));
        const am = amSec ? runSection(amSec, st) : 0;
        if (amCard)  amCard.style.display  = am ? '' : 'none';
        if (amGrand) { amGrand.style.display = am ? '' : 'none'; const g = amGrand.querySelector('.grand-number'); if (g) g.textContent = am; }

        // the numbers that print: total card and grand total follow the filters, exactly as before
        const tc = document.querySelector('.c-total .stat-number'); if (tc) tc.textContent = total;
        document.querySelectorAll('.grand-card:not(.amana-grand-card) .grand-number').forEach(g => g.textContent = total);
        if (empty) empty.style.display = (total === 0 && stockSec.length) ? '' : 'none';

        // headline numbers
        const vis = stockSec.flatMap(sec => Array.from(sec.querySelectorAll('tr.car-row')).filter(tr => tr.style.display !== 'none'));
        const res = vis.filter(tr => tr.classList.contains('res-row')).length;
        const ages = vis.map(tr => tr.getAttribute('data-age')).filter(a => a !== '' && a != null).map(Number);
        countTo('total', total); countTo('av', total - res); countTo('res', res); countTo('am', am);
        countTo('age', ages.length ? Math.round(ages.reduce((a, b) => a + b, 0) / ages.length) : 0);

        allSec.forEach(sec => decorate(sec, total));
        buildJump();
        if (!silentUrl) syncUrl(st);
    }

    /* ════ ring + colour dots on each branch header ════ */
    function decorate(sec, total) {
        const n = sec._n || 0;
        const isAm = sec.getAttribute('data-branch') === '__amana__';
        const pct = isAm ? 100 : (total ? Math.round(n * 100 / total) : 0);
        const ring = sec.querySelector('.bh-ring');
        if (ring) {
            const r = 18, c = 2 * Math.PI * r;
            if (!ring._built) {
                ring.innerHTML = '<svg width="100%" height="100%" viewBox="0 0 46 46"><circle class="bg" cx="23" cy="23" r="' + r + '" fill="none" stroke-width="5"></circle>' +
                                 '<circle class="fg" cx="23" cy="23" r="' + r + '" fill="none" stroke-width="5" stroke-dasharray="' + c.toFixed(1) + '" stroke-dashoffset="' + c.toFixed(1) + '"></circle></svg><em></em>';
                ring._built = true;
            }
            ring.querySelector('em').textContent = isAm ? n : pct + '%';
            const fg = ring.querySelector('.fg');
            requestAnimationFrame(() => fg.setAttribute('stroke-dashoffset', (c * (1 - pct / 100)).toFixed(1)));
            ring.title = isAm ? '' : (AR ? 'حصة الفرع من المخزون' : "branch's share of stock");
        }
        const dots = sec.querySelector('.bh-dots');
        if (dots) {
            const m = {};
            sec.querySelectorAll('tr.car-row').forEach(tr => {
                if (tr.style.display === 'none') return;
                const k = tr.getAttribute('data-sw') + '|' + tr.getAttribute('data-cl');
                m[k] = (m[k] || 0) + 1;
            });
            const list = Object.entries(m).sort((a, b) => b[1] - a[1]);
            dots.innerHTML = list.slice(0, 7).map(([k, v]) => {
                const [sw, cl] = k.split('|');
                return '<span title="' + cl.replace(/"/g, '&quot;') + '"><i style="background:' + sw + '"></i>' + v + '</span>';
            }).join('') + (list.length > 7 ? '<span>+' + (list.length - 7) + '</span>' : '');
        }
    }

    /* ════ jump bar + scroll tracking ════ */
    function buildJump() {
        if (!jump) return;
        const act = jump.querySelector('.jp.on');
        const activeKey = act ? act.getAttribute('data-b') : null;
        jump.innerHTML = allSec.filter(sec => (sec._n || 0) > 0).map(sec =>
            '<button type="button" class="jp" data-b="' + sec.getAttribute('data-branch').replace(/"/g, '&quot;') + '" style="--bc:' + getComputedStyle(sec).getPropertyValue('--bc').trim() + '">' +
            '<i></i>' + (sec.getAttribute('data-label') || '') + ' <b>' + sec._n + '</b></button>').join('');
        jump.querySelectorAll('.jp').forEach(b => {
            if (b.getAttribute('data-b') === activeKey) b.classList.add('on');
            b.addEventListener('click', () => {
                const sec = allSec.find(s => s.getAttribute('data-branch') === b.getAttribute('data-b'));
                if (!sec) return;
                jump._hold = { key: b.getAttribute('data-b'), until: Date.now() + 900 };
                spy();
                sec.scrollIntoView({ behavior: 'smooth', block: 'start' });
            });
        });
        spy();
    }
    function spy() {
        if (!jump) return;
        const line = (parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--jb-h')) || 56) + 90;
        const visible = allSec.filter(s => s.style.display !== 'none');
        let cur = null;
        visible.forEach(sec => { if (sec.getBoundingClientRect().top <= line) cur = sec; });
        if (!cur) cur = visible[0] || null;
        // at the very bottom the last sections can't reach the top line, so the last one wins
        if (innerHeight + scrollY >= document.documentElement.scrollHeight - 4 && visible.length) cur = visible[visible.length - 1];
        // a pill that was just tapped stays lit while the page glides to it
        if (jump._hold && Date.now() < jump._hold.until) cur = allSec.find(s => s.getAttribute('data-branch') === jump._hold.key) || cur;
        const key = cur ? cur.getAttribute('data-branch') : null;
        jump.querySelectorAll('.jp').forEach(b => {
            const on = b.getAttribute('data-b') === key;
            if (on && !b.classList.contains('on')) {
                const l = b.offsetLeft - jump.clientWidth / 2 + b.offsetWidth / 2;
                jump.scrollTo({ left: l, behavior: 'smooth' });
            }
            b.classList.toggle('on', on);
        });
    }
    let spyT = null;
    window.addEventListener('scroll', () => { if (spyT) return; spyT = requestAnimationFrame(() => { spyT = null; spy(); }); }, { passive: true });

    /* ════ pinned offsets: the jump bar, then the branch header, then the column titles ════ */
    function measure() {
        const root = document.documentElement.style;
        root.setProperty('--jb-h', (jump && jump.offsetHeight ? jump.offsetHeight : 0) + 'px');
        const h = document.querySelector('.table-card:not(.amana-report-card) .branch-section:not(.folded) .branch-header');
        if (h) root.setProperty('--bh-h', h.offsetHeight + 'px');
    }
    window.addEventListener('resize', measure);

    /* ════ numbers count up ════ */
    function countTo(k, target) {
        const el = document.querySelector('.kpi-n[data-k="' + k + '"]'); if (!el) return;
        const from = shown[k] || 0; shown[k] = target;
        if (from === target) { el.textContent = target; return; }
        const t0 = performance.now(), dur = from === 0 ? 1100 : 450;
        (function step(t) {
            const p = Math.min(1, (t - t0) / dur), e = 1 - Math.pow(1 - p, 3);
            el.textContent = Math.round(from + (target - from) * e);
            if (p < 1) requestAnimationFrame(step);
        })(t0);
    }

    /* ════ fold a branch away, remembered per browser ════ */
    allSec.forEach(sec => {
        const key = 'sr_fold_' + sec.getAttribute('data-branch');
        try { if (localStorage.getItem(key) === '1') sec.classList.add('folded'); } catch (e) {}
        const btn = sec.querySelector('.bh-fold');
        if (btn) btn.addEventListener('click', ev => {
            ev.stopPropagation();
            const f = sec.classList.toggle('folded');
            try { localStorage.setItem(key, f ? '1' : '0'); } catch (e) {}
            measure(); spy();
        });
    });

    /* ════ inputs: no more reloads ════ */
    function syncUrl(st) {
        try {
            const p = new URLSearchParams(location.search);
            [['search', val('search')], ['branch', st.branch], ['brand', st.brand], ['date_from', st.from], ['date_to', st.to]]
                .forEach(([k, v]) => v ? p.set(k, v) : p.delete(k));
            p.delete('print');
            history.replaceState(null, '', location.pathname + '?' + p.toString());
            document.querySelectorAll('.lang-row a').forEach(a => {
                const q = new URLSearchParams(p); q.set('lang', new URL(a.href, location.href).searchParams.get('lang') || 'ar');
                a.href = location.pathname + '?' + q.toString();
            });
        } catch (e) {}
    }
    if (form) {
        let t = null;
        form.addEventListener('submit', e => { e.preventDefault(); apply(); });
        if (form.elements.search) form.elements.search.addEventListener('input', () => { clearTimeout(t); t = setTimeout(apply, 110); });
        ['branch', 'brand', 'date_from', 'date_to'].forEach(n => { if (form.elements[n]) form.elements[n].addEventListener('change', () => apply()); });
        const reset = form.querySelector('.btn-reset');
        if (reset) reset.addEventListener('click', e => {
            e.preventDefault();
            ['search', 'branch', 'brand', 'date_from', 'date_to'].forEach(n => { if (form.elements[n]) form.elements[n].value = ''; });
            apply();
        });
    }

    /* ════ entrance: branch panels rise in one after another ════ */
    const reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if ('IntersectionObserver' in window && !reduce) {
        let q = 0;
        const io = new IntersectionObserver(entries => entries.forEach(en => {
            if (!en.isIntersecting) return;
            const el = en.target; io.unobserve(el);
            setTimeout(() => el.classList.remove('rv-wait'), (q++ % 6) * 90);
        }), { rootMargin: '0px 0px -40px 0px' });
        allSec.forEach(sec => { sec.classList.add('rv-wait'); io.observe(sec); });
        window.addEventListener('beforeprint', () => allSec.forEach(s => s.classList.remove('rv-wait')));
    }

    /* ════ hover preview of the car photo (computers only) ════ */
    const peek = document.getElementById('peek');
    if (peek && window.matchMedia && window.matchMedia('(hover: hover) and (pointer: fine)').matches) {
        const pimg = peek.querySelector('img'), plab = peek.querySelector('span');
        let cur = null;
        document.querySelectorAll('tr.car-row[data-img]').forEach(tr => {
            const src = tr.getAttribute('data-img'); if (!src) return;
            tr.addEventListener('mouseenter', () => {
                cur = tr; pimg.src = src; plab.textContent = tr.getAttribute('data-cl') || '';
                peek.classList.add('on');
            });
            tr.addEventListener('mousemove', e => {
                const w = 230, h = 140, pad = 18;
                let x = e.clientX + pad, y = e.clientY - h - 12;
                if (AR) x = e.clientX - w - pad;
                if (x + w > innerWidth - 8) x = e.clientX - w - pad;
                if (x < 8) x = e.clientX + pad;
                if (y < 8) y = e.clientY + 22;
                peek.style.left = x + 'px'; peek.style.top = y + 'px';
            });
            tr.addEventListener('mouseleave', () => { if (cur === tr) peek.classList.remove('on'); });
            tr.addEventListener('click', () => peek.classList.remove('on'));
        });
        pimg.addEventListener('error', () => peek.classList.remove('on'));
    }

    measure();
    apply(true);      // reproduce whatever the URL asked for, before anything is drawn or printed
    measure();
    window.addEventListener('load', () => { measure(); spy(); });
})();
</script>

<!-- ══════════ Car card: opens when any row is tapped ══════════ -->
<style>
@media screen {
    .car-row { cursor:pointer; }
    .car-row:focus-visible { outline:2px solid #9333ea; outline-offset:-2px; }
    .inv-table tbody tr.car-row:hover td:first-child { box-shadow:inset 3px 0 0 #9333ea; }
    html[dir="rtl"] .inv-table tbody tr.car-row:hover td:first-child { box-shadow:inset -3px 0 0 #9333ea; }
}

.cc-ov { position:fixed; inset:0; z-index:500; background:rgba(2,6,23,.74); backdrop-filter:blur(6px);
         display:none; align-items:center; justify-content:center; padding:18px; }
.cc-ov.on { display:flex; animation:ccFade .2s ease both; }
@keyframes ccFade { from { opacity:0; } to { opacity:1; } }
.cc {
    width:100%; max-width:440px; max-height:92vh; overflow-y:auto; position:relative;
    background:#0a1020; border:1px solid rgba(147,51,234,.3); border-radius:24px;
    box-shadow:0 30px 90px rgba(0,0,0,.75); color:#f1f5f9;
    animation:ccIn .32s cubic-bezier(.22,1,.36,1) both;
}
@keyframes ccIn { from { opacity:0; transform:translateY(14px) scale(.97); } to { opacity:1; transform:none; } }
.cc-top { position:absolute; top:12px; inset-inline:12px; display:flex; justify-content:space-between; z-index:5; pointer-events:none; }
.cc-top button { pointer-events:auto; width:34px; height:34px; border-radius:11px; border:1px solid rgba(255,255,255,.14);
                 background:rgba(2,6,23,.72); backdrop-filter:blur(6px); color:#e2e8f0; cursor:pointer; font-size:14px; font-family:inherit; }
.cc-top button:disabled { opacity:.3; cursor:default; }
.cc-nav { display:flex; gap:6px; }

.cc-stage { position:relative; height:170px; border-radius:24px 24px 0 0; overflow:hidden; isolation:isolate;
    background:radial-gradient(ellipse 70% 95% at 50% 112%, rgba(147,51,234,.3), transparent 70%),
               radial-gradient(ellipse 55% 70% at 50% -10%, rgba(255,255,255,.08), transparent 70%),
               linear-gradient(180deg,#101b33 0%,#0a1222 100%); }
.cc-stage::before { content:''; position:absolute; left:20%; right:20%; bottom:14px; height:14px; z-index:0;
    background:radial-gradient(ellipse at center, rgba(0,0,0,.6), transparent 70%); }
.cc-stage img { position:relative; z-index:1; display:block; width:100%; height:100%; padding:44px 26px 18px;
    object-fit:contain; object-position:center 88%; filter:drop-shadow(0 8px 12px rgba(0,0,0,.4));
    opacity:0; transition:opacity .4s ease; }
.cc-stage.ready img { opacity:1; }
.cc-stage.studio { background:radial-gradient(ellipse 85% 60% at 50% 104%, #cbd5e1, transparent 72%), linear-gradient(180deg,#fff 0%,#eef2f7 62%,#e2e8f0 100%); }
.cc-stage.studio img { mix-blend-mode:multiply; filter:none; }
.cc-stage.scene img { object-fit:cover; padding:0; filter:none; }
.cc-stage.scene::before { display:none; }
.cc-stage.matte { background:var(--stage-bg,#0a1222); }
.cc-stage .cc-ph { position:absolute; inset:0; display:flex; align-items:center; justify-content:center; font-size:64px; opacity:.25; }
.cc.res .cc-stage:not(.studio):not(.scene):not(.matte) { background:radial-gradient(ellipse 70% 95% at 50% 112%, rgba(234,179,8,.34), transparent 70%), linear-gradient(180deg,#171a2c 0%,#0f1220 100%); }

.cc-body { padding:16px 18px 18px; }
.cc-title { font-size:21px; font-weight:900; line-height:1.25; }
.cc-sub { font-size:13px; color:#94a3b8; font-weight:700; margin-top:3px; }
.cc-badges { display:flex; gap:7px; flex-wrap:wrap; margin-top:11px; }
.cc-b { display:inline-flex; align-items:center; gap:5px; height:26px; padding:0 11px; border-radius:50px; font-size:12px; font-weight:900; }
.cc-b.available   { background:rgba(34,197,94,.14);  color:#4ade80; border:1px solid rgba(34,197,94,.3); }
.cc-b.reserved    { background:rgba(234,179,8,.16);  color:#fde047; border:1px solid rgba(234,179,8,.38); }
.cc-b.consignment { background:rgba(245,158,11,.15); color:#fbbf24; border:1px solid rgba(245,158,11,.35); }
.cc-b.g { background:rgba(34,197,94,.1);  color:#4ade80; border:1px solid rgba(34,197,94,.25); }
.cc-b.a { background:rgba(245,158,11,.1); color:#fbbf24; border:1px solid rgba(245,158,11,.28); }
.cc-b.r { background:rgba(239,68,68,.12); color:#f87171; border:1px solid rgba(239,68,68,.3); }

.cc-grid { display:grid; grid-template-columns:1fr 1fr; gap:8px; margin-top:14px; }
.cc-f { background:rgba(15,23,42,.9); border:1px solid rgba(255,255,255,.07); border-radius:13px; padding:9px 12px; min-width:0; }
.cc-f.wide { grid-column:1 / -1; }
.cc-f label { display:block; font-size:10.5px; font-weight:800; color:#64748b; margin-bottom:3px; }
.cc-f .v { font-size:14px; font-weight:800; display:flex; align-items:center; gap:7px; overflow-wrap:anywhere; }
.cc-f .v i { width:15px; height:15px; border-radius:50%; border:1px solid rgba(255,255,255,.3); display:inline-block; flex-shrink:0; }
.cc-ch { font-family:ui-monospace,'Courier New',monospace; letter-spacing:.05em; color:#a3e635; }
.cc-copy { margin-inline-start:auto; height:26px; padding:0 10px; border-radius:8px; border:1px solid rgba(163,230,53,.35);
           background:rgba(163,230,53,.08); color:#bef264; font-size:11.5px; font-weight:800; cursor:pointer; font-family:inherit; white-space:nowrap; }
.cc-note { margin-top:8px; background:rgba(147,51,234,.07); border:1px solid rgba(147,51,234,.2); border-radius:13px;
           padding:10px 12px; font-size:13px; line-height:1.6; color:#e2e8f0; }
.cc-actions { display:grid; grid-template-columns:repeat(auto-fit,minmax(110px,1fr)); gap:8px; margin-top:14px; }
.cc-actions a { display:flex; align-items:center; justify-content:center; gap:6px; height:42px; border-radius:12px;
                text-decoration:none; font-size:13px; font-weight:800; color:#fff; transition:transform .15s; }
.cc-actions a:hover { transform:translateY(-2px); }
.cc-actions .t { background:#2563eb; }
.cc-actions .q { background:rgba(255,255,255,.07); border:1px solid rgba(255,255,255,.12); }
.cc-actions .e { background:#9333ea; }

@media (max-width:600px) {
    .cc-ov { align-items:flex-end; padding:0; }
    .cc { max-width:none; border-radius:24px 24px 0 0; max-height:90vh; animation:ccUp .34s cubic-bezier(.22,1,.36,1) both; }
    @keyframes ccUp { from { transform:translateY(100%); } to { transform:none; } }
    .cc-stage { height:150px; }
}
@media print { .cc-ov { display:none !important; } }
</style>

<div class="cc-ov" id="ccOv" role="dialog" aria-modal="true" aria-hidden="true">
    <div class="cc" id="cc">
        <div class="cc-top">
            <button type="button" id="ccClose" aria-label="close">✕</button>
            <div class="cc-nav">
                <button type="button" id="ccPrev" aria-label="previous"><?= $lang === 'ar' ? '›' : '‹' ?></button>
                <button type="button" id="ccNext" aria-label="next"><?= $lang === 'ar' ? '‹' : '›' ?></button>
            </div>
        </div>
        <div id="ccContent"></div>
    </div>
</div>

<script>
(function () {
    const CARS = <?= json_encode($cardData, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;
    const LANG = <?= json_encode($lang) ?>;
    const CAN_EDIT = <?= $canEditCar ? 'true' : 'false' ?>;
    const T = <?= json_encode($lang === 'ar' ? [
        'available' => 'متاحة', 'reserved' => '🔒 محجوزة', 'consignment' => '🔶 أمانة', 'day' => 'يوم في المخزون',
        'color' => 'اللون', 'branch' => 'الفرع', 'chassis' => 'رقم الشاسيه', 'arrived' => 'تاريخ الإضافة',
        'by' => 'أضيفت بواسطة', 'dealer' => 'التاجر', 'since' => 'خرجت أمانة بتاريخ', 'notes' => 'ملاحظات',
        'copy' => 'نسخ', 'copied' => '✓ تم النسخ', 'timeline' => '🕐 رحلة السيارة', 'qr' => '🔳 كارت QR', 'edit' => '✏️ تعديل',
    ] : [
        'available' => 'Available', 'reserved' => '🔒 Reserved', 'consignment' => '🔶 Consignment', 'day' => 'days in stock',
        'color' => 'Colour', 'branch' => 'Branch', 'chassis' => 'Chassis No.', 'arrived' => 'Added on',
        'by' => 'Added by', 'dealer' => 'Dealer', 'since' => 'Out on consignment since', 'notes' => 'Notes',
        'copy' => 'Copy', 'copied' => '✓ Copied', 'timeline' => '🕐 Vehicle journey', 'qr' => '🔳 QR card', 'edit' => '✏️ Edit',
    ], JSON_UNESCAPED_UNICODE) ?>;
    const SW = { white:'#f8fafc','pearl white':'#f1f5f9',black:'#111827',silver:'#cbd5e1',grey:'#6b7280',gray:'#6b7280',
                 red:'#dc2626',blue:'#2563eb',navy:'#1e3a8a',green:'#16a34a',gold:'#d4af37',beige:'#e0d5c0',brown:'#78350f',
                 orange:'#ea580c',yellow:'#eab308',purple:'#7c3aed',bronze:'#a97142',champagne:'#e6d7b8' };

    const ov = document.getElementById('ccOv'), box = document.getElementById('cc'), content = document.getElementById('ccContent');
    const esc = v => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
    let rows = [], idx = -1;

    function ageCls(d) { return d == null ? '' : d < 30 ? 'g' : d < 90 ? 'a' : 'r'; }

    function render(id) {
        const c = CARS[id]; if (!c) return;
        box.classList.toggle('res', c.status === 'reserved');
        const sw = SW[(c.colorEn || '').toLowerCase()] || '#64748b';
        let h = '<div class="cc-stage" id="ccStage">' + (c.img ? '<img id="ccImg" src="' + esc(c.img) + '" alt="">' : '<div class="cc-ph">🚗</div>') + '</div>';
        h += '<div class="cc-body"><div class="cc-title">' + esc(c.brand + ' ' + c.model) + '</div>';
        h += '<div class="cc-sub">' + esc([c.trim, c.year].filter(Boolean).join(' · ')) + '</div>';
        h += '<div class="cc-badges"><span class="cc-b ' + c.status + '">' + esc(T[c.status]) + '</span>';
        if (c.days != null) h += '<span class="cc-b ' + ageCls(c.days) + '">⏱ ' + c.days + ' ' + esc(T.day) + '</span>';
        h += '</div><div class="cc-grid">';
        h += '<div class="cc-f"><label>' + esc(T.color) + '</label><div class="v"><i style="background:' + sw + '"></i>' + esc(c.color) + '</div></div>';
        h += '<div class="cc-f"><label>' + esc(T.branch) + '</label><div class="v">📍 ' + esc(c.branch) + '</div></div>';
        h += '<div class="cc-f wide"><label>' + esc(T.chassis) + '</label><div class="v"><span class="cc-ch">' + esc(c.chassis) + '</span>' +
             '<button type="button" class="cc-copy" id="ccCopy">' + esc(T.copy) + '</button></div></div>';
        if (c.arrived) h += '<div class="cc-f"><label>' + esc(T.arrived) + '</label><div class="v">' + esc(c.arrived) + '</div></div>';
        if (c.by)      h += '<div class="cc-f"><label>' + esc(T.by) + '</label><div class="v">' + esc(c.by) + '</div></div>';
        if (c.status === 'consignment') {
            h += '<div class="cc-f"><label>' + esc(T.dealer) + '</label><div class="v">👤 ' + esc(c.dealer || '—') + '</div></div>';
            h += '<div class="cc-f"><label>' + esc(T.since) + '</label><div class="v">' + esc(c.since || '—') + '</div></div>';
        }
        h += '</div>';
        if (c.notes) h += '<div class="cc-note">📝 ' + esc(c.notes) + '</div>';
        h += '<div class="cc-actions"><a class="t" href="vehicle_timeline.php?id=' + c.id + '&lang=' + LANG + '">' + esc(T.timeline) + '</a>';
        h += '<a class="q" href="qr.php?c=' + encodeURIComponent(c.chassis) + '&lang=' + LANG + '">' + esc(T.qr) + '</a>';
        if (CAN_EDIT && c.status !== 'consignment') h += '<a class="e" href="edit_vehicle.php?id=' + c.id + '&lang=' + LANG + '">' + esc(T.edit) + '</a>';
        h += '</div></div>';
        content.innerHTML = h;

        document.getElementById('ccCopy').addEventListener('click', function () {
            const b = this, done = () => { b.textContent = T.copied; setTimeout(() => b.textContent = T.copy, 1400); };
            if (navigator.clipboard && window.isSecureContext) navigator.clipboard.writeText(c.chassis).then(done, done);
            else { const ta = document.createElement('textarea'); ta.value = c.chassis; document.body.appendChild(ta); ta.select();
                   try { document.execCommand('copy'); } catch (e) {} ta.remove(); done(); }
        });
        const img = document.getElementById('ccImg');
        if (img) stage(img, document.getElementById('ccStage'));

        document.getElementById('ccPrev').disabled = idx <= 0;
        document.getElementById('ccNext').disabled = idx >= rows.length - 1;
    }

    /* Same showroom stage as the dashboard: pick a backdrop from the photo's
       edges, then zoom so the car fills the stage with its wheels on the floor. */
    function stage(img, st) {
        const PAD = { x: 26, t: 44, b: 18 };
        function go() {
            try {
                const w = 120, h = Math.max(24, Math.round(w * img.naturalHeight / img.naturalWidth));
                const cv = document.createElement('canvas'); cv.width = w; cv.height = h;
                const cx = cv.getContext('2d', { willReadFrequently: true }); cx.drawImage(img, 0, 0, w, h);
                const d = cx.getImageData(0, 0, w, h).data, at = (x, y) => { const i = (y * w + x) * 4; return [d[i], d[i+1], d[i+2]]; };
                const ring = [];
                for (let x = 1; x < w - 1; x += 5) { ring.push(at(x, 1)); ring.push(at(x, h - 2)); }
                for (let y = 1; y < h - 1; y += 3) { ring.push(at(1, y)); ring.push(at(w - 2, y)); }
                const m = [0,1,2].map(k => ring.reduce((a, p) => a + p[k], 0) / ring.length);
                const spread = Math.sqrt(ring.reduce((a, p) => a + (p[0]-m[0])**2 + (p[1]-m[1])**2 + (p[2]-m[2])**2, 0) / ring.length);
                const lum = .299*m[0] + .587*m[1] + .114*m[2];
                if (spread > 34) st.classList.add('scene');
                else {
                    if (lum > 226) st.classList.add('studio');
                    else { st.classList.add('matte'); st.style.setProperty('--stage-bg', 'rgb(' + m.map(Math.round).join(',') + ')'); }
                    let x0 = w, y0 = h, x1 = -1, y1 = -1;
                    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
                        const p = at(x, y);
                        if (Math.abs(p[0]-m[0]) + Math.abs(p[1]-m[1]) + Math.abs(p[2]-m[2]) > 60) {
                            if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y;
                        }
                    }
                    const fw = (x1-x0+1)/w, fh = (y1-y0+1)/h;
                    if (x1 > 0 && fw > .08 && fh > .08 && !(fw > .97 && fh > .97)) {
                        const sw = st.clientWidth - PAD.x * 2, sh = st.clientHeight - PAD.t - PAD.b;
                        const nw = img.naturalWidth, nh = img.naturalHeight;
                        const cw = (x1+1-x0)/w*nw, ch = (y1+1-y0)/h*nh, k = Math.min(sw/cw, sh/ch);
                        Object.assign(img.style, { position:'absolute', maxWidth:'none', padding:'0', objectFit:'fill',
                            width:(nw*k)+'px', height:(nh*k)+'px',
                            left:(PAD.x + (sw - cw*k)/2 - x0/w*nw*k)+'px', top:(PAD.t + (sh - ch*k) - y0/h*nh*k)+'px' });
                    }
                }
            } catch (e) {}
            st.classList.add('ready');
        }
        img.addEventListener('error', () => { img.remove(); st.insertAdjacentHTML('afterbegin', '<div class="cc-ph">🚗</div>'); }, { once: true });
        if (img.complete && img.naturalWidth) go(); else img.addEventListener('load', go, { once: true });
    }

    function open(tr) {
        rows = Array.from(document.querySelectorAll('tr.car-row')).filter(r => r.offsetParent !== null);
        idx = rows.indexOf(tr);
        render(tr.getAttribute('data-id'));
        ov.classList.add('on'); ov.setAttribute('aria-hidden', 'false');
        document.body.style.overflow = 'hidden';
    }
    function close() {
        ov.classList.remove('on'); ov.setAttribute('aria-hidden', 'true');
        document.body.style.overflow = '';
        if (rows[idx]) rows[idx].focus({ preventScroll: true });
    }
    function step(d) {
        const n = idx + d; if (n < 0 || n >= rows.length) return;
        idx = n; render(rows[idx].getAttribute('data-id'));
        rows[idx].scrollIntoView({ block: 'center', behavior: 'smooth' });
    }

    document.querySelectorAll('tr.car-row').forEach(tr => {
        tr.addEventListener('click', e => { if (e.target.closest('a,button')) return; open(tr); });
        tr.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open(tr); } });
    });
    document.getElementById('ccClose').addEventListener('click', close);
    document.getElementById('ccPrev').addEventListener('click', () => step(-1));
    document.getElementById('ccNext').addEventListener('click', () => step(1));
    ov.addEventListener('click', e => { if (e.target === ov) close(); });
    document.addEventListener('keydown', e => {
        if (!ov.classList.contains('on')) return;
        if (e.key === 'Escape') close();
        if (e.key === 'ArrowDown' || e.key === (LANG === 'ar' ? 'ArrowLeft' : 'ArrowRight')) step(1);
        if (e.key === 'ArrowUp'   || e.key === (LANG === 'ar' ? 'ArrowRight' : 'ArrowLeft')) step(-1);
    });
})();
</script>
</body>
</html>
